import assert from "node:assert/strict";
import test from "node:test";
import { ApplyCoordinationError, bindApplyCoordination, createMemoryApplyCoordinationStore } from "../src/apply-coordination.js";
import { ApplyPortError, type ExecutorPorts } from "../src/executor.js";

const a="a".repeat(64),b="b".repeat(64),c="c".repeat(64);
test("nonce consumption is atomic and permanently rejects replay",async()=>{let now=1000;const store=createMemoryApplyCoordinationStore({nowMs:()=>now});const request={keyDigest:a,valueDigest:b,expiresAtMs:2000,epoch:1};const outcomes=await Promise.all([store.consumeNonce(request),store.consumeNonce(request)]);assert.deepEqual(outcomes.sort(),["consumed","replayed"]);now=3000;assert.equal(await store.consumeNonce({...request,valueDigest:c,expiresAtMs:4000}),"replayed");});
test("leases exclude contenders and advance fencing tokens",async()=>{let now=1000;const store=createMemoryApplyCoordinationStore({nowMs:()=>now});const first=await store.acquireLease({keyDigest:a,holderDigest:b,expiresAtMs:2000,epoch:1});assert.ok(first);assert.equal(await store.acquireLease({keyDigest:a,holderDigest:c,expiresAtMs:2000,epoch:1}),null);assert.equal(await first.valid(),true);assert.equal(await first.release(),true);const second=await store.acquireLease({keyDigest:a,holderDigest:c,expiresAtMs:2500,epoch:1});assert.ok(second);assert.ok(second.fencingToken>first.fencingToken);assert.equal(await first.valid(),false);});
test("expired and stale lease owners fail closed",async()=>{let now=1000;const store=createMemoryApplyCoordinationStore({nowMs:()=>now});const first=await store.acquireLease({keyDigest:a,holderDigest:b,expiresAtMs:1500,epoch:1});assert.ok(first);now=1600;assert.equal(await first.valid(),false);assert.equal(await first.renew(2000),false);const second=await store.acquireLease({keyDigest:a,holderDigest:c,expiresAtMs:2000,epoch:1});assert.ok(second);assert.equal(await first.release(),false);});
test("invalid digests, epochs and lifetimes fail before state change",async()=>{const store=createMemoryApplyCoordinationStore({nowMs:()=>1000,maxLifetimeMs:1000});await assert.rejects(store.consumeNonce({keyDigest:"raw",valueDigest:b,expiresAtMs:1500,epoch:1}),error=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-001");await assert.rejects(store.acquireLease({keyDigest:a,holderDigest:b,expiresAtMs:3000,epoch:1}),ApplyCoordinationError);await assert.rejects(store.acquireLease({keyDigest:a,holderDigest:b,expiresAtMs:1500,epoch:2}),ApplyCoordinationError);});
test("executor binding hashes nonce and scope before crossing the adapter boundary",async()=>{const seen:string[]=[];const store={consumeNonce:async(value:{keyDigest:string;valueDigest:string;expiresAtMs:number;epoch:number})=>{seen.push(value.keyDigest,value.valueDigest);return"consumed" as const;},acquireLease:async(value:{keyDigest:string;holderDigest:string;expiresAtMs:number;epoch:number})=>{seen.push(value.keyDigest,value.holderDigest);return{fencingToken:1,renew:async()=>true,valid:async()=>true,release:async()=>true};}};const base={} as Omit<ExecutorPorts,"acquireLease"|"consumeNonce">;const ports=bindApplyCoordination(base,store,{holderDigest:c,expiresAtMs:2000,epoch:1});assert.equal(await ports.consumeNonce("raw-secret-nonce"),true);assert.ok(await ports.acquireLease("raw-scope"));assert.equal(seen.includes("raw-secret-nonce")||seen.includes("raw-scope"),false);assert.ok(seen.every(value=>/^[a-f0-9]{64}$/u.test(value)));});
test("executor binding preserves stable coordination failure classes",async()=>{const base={} as Omit<ExecutorPorts,"acquireLease"|"consumeNonce">;for(const [code,failureClass] of [["YKP-COORD-004","authentication"],["YKP-COORD-005","authorization"],["YKP-COORD-002","provider"],["YKP-COORD-001","invariant"]] as const){const store={consumeNonce:async()=>{throw new ApplyCoordinationError(code);},acquireLease:async()=>{throw new ApplyCoordinationError(code);}};const ports=bindApplyCoordination(base,store,{holderDigest:c,expiresAtMs:2000,epoch:1});await assert.rejects(ports.consumeNonce("bounded-nonce-value-000"),(error:unknown)=>error instanceof ApplyPortError&&error.failureClass===failureClass);await assert.rejects(ports.acquireLease(a),(error:unknown)=>error instanceof ApplyPortError&&error.failureClass===failureClass);}});
