import assert from "node:assert/strict";
import test from "node:test";
import { ApplyCoordinationError } from "../src/apply-coordination.js";
import { createApplyCoordinationHttpStore } from "../src/apply-coordination-http.js";

const MEDIA="application/yukh-coordination-primitives+json;version=1",digest="a".repeat(64),holder="b".repeat(64),expires=Date.parse("2026-08-03T12:00:30.000Z");
function response(body:Record<string,unknown>,status=200):Response{return new Response(JSON.stringify(body,Object.keys(body).sort()),{status,headers:{"content-type":MEDIA}});}
function options(fetch:typeof globalThis.fetch){return{baseUri:"https://coordination.invalid",epoch:7,deadlineMs:1000,authenticate:async()=>({credential:"synthetic-secret",proof:"a.b.c"}),fetch};}

test("HTTPS coordination adapter performs one bounded lifecycle",async()=>{const requests:{url:string;redirect:RequestRedirect|undefined}[]=[],replies=[response({expires_at:"2026-08-03T12:00:30.000Z",fencing_token:1,lease_capability:"opaque-one",outcome:"acquired",specversion:"1"}),response({outcome:"valid",specversion:"1"}),response({expires_at:"2026-08-03T12:00:40.000Z",fencing_token:2,lease_capability:"opaque-two",outcome:"renewed",specversion:"1"}),response({outcome:"released",specversion:"1"})],fetch=async(url:string|URL|Request,init?:RequestInit)=>{requests.push({url:String(url),redirect:init?.redirect});return replies.shift()!;};const store=createApplyCoordinationHttpStore(options(fetch as typeof globalThis.fetch)),lease=await store.acquireLease({keyDigest:digest,holderDigest:holder,expiresAtMs:expires,epoch:7});assert.ok(lease);assert.equal(lease.fencingToken,1);assert.equal(await lease.valid(),true);assert.equal(await lease.renew(Date.parse("2026-08-03T12:00:40.000Z")),true);assert.equal(lease.fencingToken,2);assert.equal(await lease.release(),true);assert.equal(requests.length,4);assert.ok(requests.every(value=>value.redirect==="manual"&&value.url.startsWith("https://coordination.invalid/")));});

test("nonce replay and lease contention are closed outcomes",async()=>{const replies=[response({outcome:"replayed",specversion:"1"}),response({code:"conflict",status:409,title:"conflict",type:"urn:yukh:coordination-primitives:problem:conflict"},409)],fetch=async()=>replies.shift()!;const store=createApplyCoordinationHttpStore(options(fetch as typeof globalThis.fetch));assert.equal(await store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),"replayed");assert.equal(await store.acquireLease({keyDigest:digest,holderDigest:holder,expiresAtMs:expires,epoch:7}),null);});

test("transport failure is single-attempt, bounded and sanitized",async()=>{let calls=0;const store=createApplyCoordinationHttpStore(options((async()=>{calls++;throw new Error("provider body private");}) as typeof globalThis.fetch));await assert.rejects(store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002"&&!error.message.includes("private"));assert.equal(calls,1);const oversized=createApplyCoordinationHttpStore(options((async()=>new Response("x".repeat(4097),{status:200,headers:{"content-type":MEDIA}})) as typeof globalThis.fetch));await assert.rejects(oversized.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-001");});

test("one deadline bounds authentication and the response body",async()=>{let authSignal:AbortSignal|undefined;const authStore=createApplyCoordinationHttpStore({...options(globalThis.fetch),deadlineMs:10,authenticate:request=>{authSignal=request.signal;return new Promise(()=>{});}});await assert.rejects(authStore.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002");assert.equal(authSignal?.aborted,true);const stream=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new TextEncoder().encode('{"outcome":"consumed",'));}}),bodyStore=createApplyCoordinationHttpStore({...options((async()=>new Response(stream,{status:200,headers:{"content-type":MEDIA}})) as typeof globalThis.fetch),deadlineMs:10});await assert.rejects(bodyStore.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002");});

test("adapter rejects ambient and mismatched configuration before HTTP",async()=>{assert.throws(()=>createApplyCoordinationHttpStore({...options(globalThis.fetch),baseUri:"http://coordination.invalid"}),/invalid coordination configuration/u);let calls=0;const store=createApplyCoordinationHttpStore(options((async()=>{calls++;throw new Error("unexpected");}) as typeof globalThis.fetch));await assert.rejects(store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:8}),/apply coordination failed/u);assert.equal(calls,0);});
