import assert from "node:assert/strict";
import { mkdtemp, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { parseApplyCliArgs, readApprovalArtifact, readExclusiveWorkspaceFile, readRunnerCapsule } from "../src/apply-runtime-input.js";

const args=["--mode","apply","--owner","synthetic-owner","--repository","synthetic-repository","--project-number","17","--issue-number","7","--approved-plan-id","a".repeat(64),"--approval-file","approval.json","--approval-public-key-file","approval.pem","--environment","protected-synthetic","--github-read-token-fd","3","--github-write-token-fd","4","--host-capsule-fd","5"];
test("apply CLI accepts only explicit native or versioned legacy modes and distinct credential descriptors",()=>{const value=parseApplyCliArgs(args),legacy=parseApplyCliArgs(args.map(value=>value==="apply"?"legacy-apply-v1":value));assert.equal(value.mode,"apply");assert.equal(legacy.mode,"legacy-apply-v1");assert.equal(value.readTokenFd,3);assert.equal(value.writeTokenFd,4);assert.equal(value.hostCapsuleFd,5);for(const bad of [[...args,"--force","true"],args.map(value=>value==="apply"?"legacy-apply":value),args.map(value=>value==="4"?"3":value)])assert.throws(()=>parseApplyCliArgs(bad));});
test("protected artifacts are bounded regular files beneath the workspace",async()=>{const root=await mkdtemp(join(tmpdir(),"yukh-apply-input-"));await writeFile(join(root,"approval.json"),'{"schema":1}',{mode:0o600});assert.equal((await readApprovalArtifact(root,"approval.json") as {schema:number}).schema,1);await symlink(join(root,"approval.json"),join(root,"link.json"));await assert.rejects(readExclusiveWorkspaceFile(root,"link.json"));await assert.rejects(readExclusiveWorkspaceFile(root,"../outside"));});
test("Action capsule is an exclusive mode-0600 basename beneath runner temp",async()=>{const root=await mkdtemp(join(tmpdir(),"yukh-host-capsule-"));await writeFile(join(root,"capsule.json"),"{}",{mode:0o600});assert.equal(await readRunnerCapsule(root,"capsule.json"),"{}");await writeFile(join(root,"open.json"),"{}",{mode:0o644});await assert.rejects(readRunnerCapsule(root,"open.json"));await assert.rejects(readRunnerCapsule(root,"../capsule.json"));});
