import assert from "node:assert/strict";
import test from "node:test";
import { ApplyCoordinationError } from "../src/apply-coordination.js";
import { createApplyCoordinationHttpStore } from "../src/apply-coordination-http.js";

const MEDIA="application/yukh-coordination-primitives+json;version=1",digest="a".repeat(64),holder="b".repeat(64),expires=Date.parse("2026-08-03T12:00:30.000Z");
function response(body:Record<string,unknown>,status=200):Response{return new Response(JSON.stringify(body,Object.keys(body).sort()),{status,headers:{"content-type":MEDIA}});}
function options(fetch:typeof globalThis.fetch){return{baseUri:"https://coordination.invalid",epoch:7,deadlineMs:1000,authenticate:async()=>({credential:"synthetic-secret",proof:"a.b.c"}),fetch};}

test("HTTPS coordination adapter performs one bounded lifecycle",async()=>{const requests:{url:string;redirect:RequestRedirect|undefined}[]=[],replies=[response({expires_at:"2026-08-03T12:00:30.000Z",fencing_token:1,lease_capability:"opaque-one",outcome:"acquired",specversion:"1"}),response({outcome:"valid",specversion:"1"}),response({expires_at:"2026-08-03T12:00:40.000Z",fencing_token:2,lease_capability:"opaque-two",outcome:"renewed",specversion:"1"}),response({outcome:"released",specversion:"1"})],fetch=async(url:string|URL|Request,init?:RequestInit)=>{requests.push({url:String(url),redirect:init?.redirect});return replies.shift()!;};const store=createApplyCoordinationHttpStore(options(fetch as typeof globalThis.fetch)),lease=await store.acquireLease({keyDigest:digest,holderDigest:holder,expiresAtMs:expires,epoch:7});assert.ok(lease);assert.equal(lease.fencingToken,1);assert.equal(await lease.valid(),true);assert.equal(await lease.renew(Date.parse("2026-08-03T12:00:40.000Z")),true);assert.equal(lease.fencingToken,2);assert.equal(await lease.release(),true);assert.equal(requests.length,4);assert.ok(requests.every(value=>value.redirect==="manual"&&value.url.startsWith("https://coordination.invalid/")));});

test("nonce replay and lease contention are closed outcomes",async()=>{const replies=[response({outcome:"replayed",specversion:"1"}),response({code:"conflict",status:409,title:"conflict",type:"urn:yukh:coordination-primitives:problem:conflict"},409)],fetch=async()=>replies.shift()!;const store=createApplyCoordinationHttpStore(options(fetch as typeof globalThis.fetch));assert.equal(await store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),"replayed");assert.equal(await store.acquireLease({keyDigest:digest,holderDigest:holder,expiresAtMs:expires,epoch:7}),null);});

test("coordination authentication and authorization remain distinct and redacted",async()=>{for(const [status,code] of [[401,"YKP-COORD-004"],[403,"YKP-COORD-005"]] as const){const store=createApplyCoordinationHttpStore(options((async()=>response({code:"private-provider-detail",status,title:"denied",type:"urn:problem"},status)) as typeof globalThis.fetch));await assert.rejects(store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code===code&&!error.message.includes("private"));}});

test("transport failure is single-attempt, bounded and sanitized",async()=>{let calls=0;const store=createApplyCoordinationHttpStore(options((async()=>{calls++;throw new Error("provider body private");}) as typeof globalThis.fetch));await assert.rejects(store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002"&&!error.message.includes("private"));assert.equal(calls,1);const oversized=createApplyCoordinationHttpStore(options((async()=>new Response("x".repeat(4097),{status:200,headers:{"content-type":MEDIA}})) as typeof globalThis.fetch));await assert.rejects(oversized.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-001");});

test("one deadline bounds authentication and the response body",async()=>{let authSignal:AbortSignal|undefined;const authStore=createApplyCoordinationHttpStore({...options(globalThis.fetch),deadlineMs:10,authenticate:request=>{authSignal=request.signal;return new Promise(()=>{});}});await assert.rejects(authStore.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002");assert.equal(authSignal?.aborted,true);const stream=new ReadableStream<Uint8Array>({start(controller){controller.enqueue(new TextEncoder().encode('{"outcome":"consumed",'));}}),bodyStore=createApplyCoordinationHttpStore({...options((async()=>new Response(stream,{status:200,headers:{"content-type":MEDIA}})) as typeof globalThis.fetch),deadlineMs:10});await assert.rejects(bodyStore.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7}),(error:unknown)=>error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-002");});

test("adapter rejects ambient and mismatched configuration before HTTP",async()=>{assert.throws(()=>createApplyCoordinationHttpStore({...options(globalThis.fetch),baseUri:"http://coordination.invalid"}),/invalid coordination configuration/u);let calls=0;const store=createApplyCoordinationHttpStore(options((async()=>{calls++;throw new Error("unexpected");}) as typeof globalThis.fetch));await assert.rejects(store.consumeNonce({keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:8}),/apply coordination failed/u);assert.equal(calls,0);});

test("independent clients preserve replay exclusion and monotonic fencing across restart",async()=>{const nonces=new Set<string>(),leases=new Map<string,{capability:string;token:number;released:boolean}>(),capabilities=new Map<string,{scope:string;token:number}>();let token=0,calls=0;const service:typeof globalThis.fetch=async(input,init)=>{calls++;const path=new URL(String(input)).pathname,body=JSON.parse(String(init?.body));if(path.endsWith("nonces:consume")){const replayed=nonces.has(body.scope_digest);nonces.add(body.scope_digest);return response({outcome:replayed?"replayed":"consumed",specversion:"1"});}if(path.endsWith("leases:acquire")){const current=leases.get(body.scope_digest);if(current&&!current.released)return response({code:"conflict",status:409,title:"conflict",type:"urn:problem"},409);const next={capability:`opaque-${++token}`,token,released:false};leases.set(body.scope_digest,next);capabilities.set(next.capability,{scope:body.scope_digest,token:next.token});return response({expires_at:body.expires_at,fencing_token:next.token,lease_capability:next.capability,outcome:"acquired",specversion:"1"});}const observed=capabilities.get(body.lease_capability),current=observed&&leases.get(observed.scope),valid=Boolean(observed&&current&&!current.released&&current.token===observed.token);if(path.endsWith("leases:inspect"))return response({outcome:valid?"valid":"stale",specversion:"1"});if(path.endsWith("leases:release")){if(!valid)return response({code:"stale_fence",status:409,title:"stale",type:"urn:problem"},409);current!.released=true;return response({outcome:"released",specversion:"1"});}throw new Error("unexpected synthetic request");};const first=createApplyCoordinationHttpStore(options(service)),restarted=createApplyCoordinationHttpStore(options(service)),nonceRequest={keyDigest:digest,valueDigest:holder,expiresAtMs:expires,epoch:7},nonceOutcomes=await Promise.all([first.consumeNonce(nonceRequest),restarted.consumeNonce(nonceRequest)]);assert.deepEqual(nonceOutcomes.sort(),["consumed","replayed"]);const leaseRequest={keyDigest:digest,holderDigest:holder,expiresAtMs:expires,epoch:7},[winner,contender]=await Promise.all([first.acquireLease(leaseRequest),restarted.acquireLease(leaseRequest)]);const lease=winner??contender;assert.ok(lease);assert.equal(winner===null||contender===null,true);assert.equal(await lease.release(),true);const afterRestart=await restarted.acquireLease(leaseRequest);assert.ok(afterRestart);assert.ok(afterRestart.fencingToken>lease.fencingToken);assert.equal(await lease.valid(),false);assert.equal(await lease.release(),false);assert.equal(calls,8);});
