import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import test from "node:test";
import { APPLY_VERSIONS, approvalSigningInputForTest, verifySignedApproval, type SignedApprovalEnvelope } from "../src/apply-approval.js";
import type { ApprovalClaims } from "../src/executor.js";

function fixture(){const pair=generateKeyPairSync("ed25519"),der=pair.publicKey.export({type:"spki",format:"der"}),fingerprint=createHash("sha256").update(der).digest("hex");const claims:ApprovalClaims={schema:1,issuerRef:"approver:synthetic",subjectRef:"subject:synthetic",repositoryRef:"repository:synthetic",projectRef:"project:synthetic",issueRef:"issue:synthetic",issueNumber:7,scopeDigest:"a".repeat(64),planId:"b".repeat(64),operationDigest:"c".repeat(64),environment:"apply",protectedEnvironment:"protected-synthetic",issuedAtMs:1000,expiresAtMs:2000,nonce:"synthetic-nonce-128-bits-plus",keyFingerprint:fingerprint,contractVersion:APPLY_VERSIONS.contract,plannerVersion:APPLY_VERSIONS.planner,snapshotVersion:APPLY_VERSIONS.snapshot,entrypointVersion:APPLY_VERSIONS.entrypoint};const unsigned={schema:1 as const,algorithm:"Ed25519" as const,keyFingerprint:fingerprint,claims};const envelope:SignedApprovalEnvelope={...unsigned,signature:sign(null,approvalSigningInputForTest(unsigned),pair.privateKey).toString("base64url")};return{pair,claims,envelope};}

test("verifies an exact Ed25519 envelope under the protected trust root",()=>{const {pair,claims,envelope}=fixture();assert.deepEqual(verifySignedApproval(envelope,{publicKey:pair.publicKey.export({type:"spki",format:"pem"}),allowedIssuerRefs:[claims.issuerRef]}),claims);});
test("rejects signature, key, issuer, fingerprint and unknown-field substitution",()=>{const {pair,claims,envelope}=fixture(),other=generateKeyPairSync("ed25519"),changedSignature=`${envelope.signature.startsWith("A")?"B":"A"}${envelope.signature.slice(1)}`;const trust={publicKey:pair.publicKey.export({type:"spki",format:"pem"}),allowedIssuerRefs:[claims.issuerRef]};for(const bad of [{...envelope,signature:changedSignature},{...envelope,keyFingerprint:"0".repeat(64)},{...envelope,claims:{...claims,issuerRef:"approver:other"}},{...envelope,unknown:true}])assert.equal(verifySignedApproval(bad,trust),null);assert.equal(verifySignedApproval(envelope,{...trust,publicKey:other.publicKey.export({type:"spki",format:"pem"})}),null);});
test("rejects changed claims and version substitution",()=>{const {pair,claims,envelope}=fixture(),trust={publicKey:pair.publicKey.export({type:"spki",format:"pem"}),allowedIssuerRefs:[claims.issuerRef]};assert.equal(verifySignedApproval({...envelope,claims:{...claims,planId:"0".repeat(64)}},trust),null);assert.equal(verifySignedApproval({...envelope,claims:{...claims,entrypointVersion:"apply-entrypoint-v2"}},trust),null);});
