import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import test from "node:test";
import { APPLY_VERSIONS, approvalSigningInputForTest, type SignedApprovalEnvelope } from "../src/apply-approval.js";
import { createMemoryApplyCoordinationStore } from "../src/apply-coordination.js";
import { runApplyEntrypoint, type ApplyEntrypointHost } from "../src/apply-entrypoint.js";
import type { ApprovalClaims } from "../src/executor.js";
import { canonicalJson, type BoundScope, type PlannedOperation, type ReconciliationPlan } from "../src/planner.js";

const digest=(value:unknown)=>createHash("sha256").update(canonicalJson(value)).digest("hex"),now=1_800_000_000_000;
const scope:BoundScope={subjectRef:"subject:synthetic",repositoryRef:"repository:synthetic",projectRef:"project:synthetic",issueRef:"issue:synthetic",issueNumber:7};
const operation:PlannedOperation={operationKey:"relationship.dependency.7.8.add",type:"add_dependency",subject:{ref:scope.subjectRef},resource:{kind:"issue_dependency",logicalKey:"7->8",scopeRef:scope.repositoryRef},action:"add",environment:"dry-run",reason:"relationship.dependency.missing",preconditions:[{kind:"dependency_absent",logicalKey:"7->8",expected:true}],dependsOn:[],desired:8};
function plan(operations:readonly PlannedOperation[]):ReconciliationPlan{const base={schema:1 as const,executable:true,diagnostics:[],observations:[],operations};return{...base,planId:digest(base)};}
function approval(pair:ReturnType<typeof generateKeyPairSync>,planValue:ReconciliationPlan,nonce:string):SignedApprovalEnvelope{const keyFingerprint=createHash("sha256").update(pair.publicKey.export({type:"spki",format:"der"})).digest("hex"),claims:ApprovalClaims={schema:1,issuerRef:"approver:synthetic",subjectRef:scope.subjectRef,repositoryRef:scope.repositoryRef,projectRef:scope.projectRef,issueRef:scope.issueRef,issueNumber:scope.issueNumber,scopeDigest:digest(scope),planId:planValue.planId,operationDigest:digest(planValue.operations),environment:"apply",protectedEnvironment:"protected-synthetic",issuedAtMs:now-1000,expiresAtMs:now+60_000,nonce,keyFingerprint,contractVersion:APPLY_VERSIONS.contract,plannerVersion:APPLY_VERSIONS.planner,snapshotVersion:APPLY_VERSIONS.snapshot,entrypointVersion:APPLY_VERSIONS.entrypoint},unsigned={schema:1 as const,algorithm:"Ed25519" as const,keyFingerprint,claims};return{...unsigned,signature:sign(null,approvalSigningInputForTest(unsigned),pair.privateKey).toString("base64url")};}
function host(replan:()=>Promise<ReconciliationPlan>,mutate:ApplyEntrypointHost["ports"]["mutate"]):ApplyEntrypointHost{return{enablement:"apply-explicitly-enabled",allowedIssuerRefs:["approver:synthetic"],holderDigest:"d".repeat(64),coordinationEpoch:3,coordinationStore:createMemoryApplyCoordinationStore({nowMs:()=>now,epoch:3}),ports:{nowMs:()=>now,replan,inspect:async()=>"ready",mutate,invalidateAfterMutation:async()=>{},verify:async()=>true,audit:async()=>{}}};}

test("authenticated entrypoint applies once and a newly approved converged plan mutates zero times",async()=>{const pair=generateKeyPairSync("ed25519"),first=plan([operation]),zero=plan([]);let replans=0,mutations=0;const firstHost=host(async()=>++replans===1?first:zero,async()=>{mutations++;});const firstReport=await runApplyEntrypoint({approvedPlanId:first.planId,protectedEnvironment:"protected-synthetic",scope,approvalArtifact:approval(pair,first,"synthetic-nonce-first-128-bits"),approvalPublicKey:pair.publicKey.export({type:"spki",format:"pem"})},firstHost);assert.equal(firstReport.status,"success");assert.equal(firstReport.remaining,0);assert.equal(mutations,1);
 const secondHost=host(async()=>zero,async()=>{mutations++;});const secondReport=await runApplyEntrypoint({approvedPlanId:zero.planId,protectedEnvironment:"protected-synthetic",scope,approvalArtifact:approval(pair,zero,"synthetic-nonce-second-128-bits"),approvalPublicKey:pair.publicKey.export({type:"spki",format:"pem"})},secondHost);assert.equal(secondReport.status,"success");assert.equal(secondReport.remaining,0);assert.equal(mutations,1);});

test("entrypoint keeps invalid approval and missing enablement before mutation",async()=>{const pair=generateKeyPairSync("ed25519"),first=plan([operation]);let mutations=0;const value=host(async()=>first,async()=>{mutations++;});value.enablement="disabled";const report=await runApplyEntrypoint({approvedPlanId:first.planId,protectedEnvironment:"protected-synthetic",scope,approvalArtifact:{invalid:true},approvalPublicKey:pair.publicKey.export({type:"spki",format:"pem"})},value);assert.equal(report.diagnostics[0]?.code,"YKP-APPLY-002");assert.equal(mutations,0);assert.doesNotMatch(JSON.stringify(report),/invalid|synthetic-owner|nonce/u);});
