import assert from "node:assert/strict";
import test from "node:test";
import { createControlledLegacyApplyHostFactory } from "../src/controlled-legacy-apply-host.js";

const MEDIA="application/yukh-coordination-primitives+json;version=1";
function json(body:unknown):Response{return new Response(JSON.stringify(body),{status:200,headers:{"content-type":"application/json","x-ratelimit-remaining":"900"}});}

test("legacy host reuses controlled gates and verifies Issue Type convergence",async()=>{
 let issueType="Task",writes=0;const issue={id:27,node_id:"I_27",number:27,body:"<!-- yukh\nschema: 1\nkind: gate\narea: delivery\npriority: P0\n-->",repository:{full_name:"example/atlas"},parent_issue_url:null,issue_dependencies_summary:{blocked_by:0,blocking:0}};
 const readFetch:typeof globalThis.fetch=async input=>{const url=String(input);if(url.endsWith("/repos/example/atlas"))return json({node_id:"R_1",owner:{type:"Organization"}});if(url.endsWith("/orgs/example/projectsV2/5"))return json({node_id:"P_5",number:5});if(url.includes("/fields?"))return json([{id:10,node_id:"F_area",name:"Area",data_type:"single_select",options:[{id:"O_delivery",name:{raw:"Delivery"}}]},{id:11,node_id:"F_priority",name:"Priority",data_type:"single_select",options:[{id:"O_p0",name:{raw:"P0"}}]}]);if(url.includes("/items?"))return json([{id:101,node_id:"PVTI_27",content:{...issue,type:{name:issueType}},fields:[{name:"Area",value:{name:{raw:"Delivery"}}},{name:"Priority",value:{name:{raw:"P0"}}}]}]);if(url.includes("/issue-types?"))return json([{node_id:"TYPE_gate",name:"Gate"},{node_id:"TYPE_task",name:"Task"}]);throw new Error("unexpected read");};
 const writeFetch:typeof globalThis.fetch=async(input,init)=>{writes++;assert.equal(String(input),"https://api.github.com/repos/example/atlas/issues/27");assert.equal(init?.method,"PATCH");const sent=JSON.parse(String(init?.body));assert.deepEqual(sent,{type:"Gate"});issueType="Gate";return json({number:27,type:{name:"Gate"}});};
 const factory=createControlledLegacyApplyHostFactory({enablement:"apply-explicitly-enabled",allowedIssuerRefs:["approver:synthetic"],holderDigest:"d".repeat(64),coordinationEpoch:7,coordination:{baseUri:"https://coordination.invalid",epoch:7,deadlineMs:1000,authenticate:async()=>({credential:"coord-secret",proof:"a.b.c"}),fetch:async()=>new Response(JSON.stringify({outcome:"valid",specversion:"1"}),{headers:{"content-type":MEDIA}})},permissions:{projects:"none",issues:"write",extraPermissions:[]},approvedKinds:["set_issue_type"],rate:{restRemaining:1000,graphqlRemaining:0},readFetch,writeFetch});
 const policy="version: 1\nfields:\n  kind: {project_field: Work Type, target: issue_type, values: {gate: Gate}}\n  area: {project_field: Area, values: {delivery: Delivery}}\n  priority: {project_field: Priority, values: {P0: P0}}\n",runtime=await factory.create({requestedScope:{ownerLogin:"example",repositoryName:"atlas",projectNumber:5,issueNumber:27},policySource:policy,readToken:"read-secret",writeToken:"write-secret"}),plan=await runtime.host.ports.replan(),operation=plan.operations[0]!;
 assert.equal(operation.type,"set_issue_type");await runtime.host.ports.mutate("set_issue_type",operation,"c".repeat(64),1);await runtime.host.ports.invalidateAfterMutation("set_issue_type",operation);assert.equal(await runtime.host.ports.verify(operation),true);assert.equal((await runtime.host.ports.replan()).operations.length,0);assert.equal(writes,1);
});
