import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { canonicalJson, type BoundScope, type PlannedOperation, type ReconciliationPlan } from "../src/planner.js";
import { ApplyPortError, executeControlledPlan, renderPublicApplyReport, type ApprovalClaims, type ExecutorPorts } from "../src/executor.js";

const scope:BoundScope={subjectRef:"subject:synthetic",repositoryRef:"repository:synthetic",projectRef:"project:synthetic",issueRef:"issue:synthetic",issueNumber:7};
const hash=(v:unknown)=>createHash("sha256").update(canonicalJson(v)).digest("hex");
const operation=(key="relationship.dependency.7.8.add",dependsOn:string[]=[]):PlannedOperation=>({operationKey:key,type:"add_dependency",subject:{ref:scope.subjectRef},resource:{kind:"issue_dependency",logicalKey:"7->8",scopeRef:scope.repositoryRef},action:"add",environment:"dry-run",reason:"relationship.dependency.missing",preconditions:[{kind:"dependency_absent",logicalKey:"7->8",expected:true}],dependsOn,desired:8});
function plan(operations:PlannedOperation[]):ReconciliationPlan{const base={schema:1 as const,executable:true,diagnostics:[],observations:[],operations};return{...base,planId:hash(base)};}
const approvedPlan=plan([operation()]),zeroPlan=plan([]);const now=1_800_000_000_000;
function claims(p=approvedPlan):ApprovalClaims{return{schema:1,issuerRef:"approver:synthetic",subjectRef:scope.subjectRef,repositoryRef:scope.repositoryRef,projectRef:scope.projectRef,issueRef:scope.issueRef,issueNumber:scope.issueNumber,scopeDigest:hash(scope),planId:p.planId,operationDigest:hash(p.operations),environment:"apply",protectedEnvironment:"protected-synthetic",issuedAtMs:now-1000,expiresAtMs:now+60_000,nonce:"synthetic-nonce-128-bits-plus",keyFingerprint:"a".repeat(64),contractVersion:"controlled-apply-v1",plannerVersion:"reconciliation-plan-v1",snapshotVersion:"rest-project-snapshot-v2",entrypointVersion:"apply-entrypoint-v1"};}
function ports(overrides:Partial<ExecutorPorts>={}):ExecutorPorts{let replans=0;return{nowMs:()=>now,verifyApproval:async()=>claims(),acquireLease:async()=>({fencingToken:1,valid:async()=>true,release:async()=>{}}),admit:async()=>true,consumeNonce:async()=>true,replan:async()=>++replans===1?approvedPlan:zeroPlan,inspect:async()=>"ready",mutate:async()=>{},invalidateAfterMutation:async()=>{},verify:async()=>true,audit:async()=>{},...overrides};}
const request={approvedPlanId:approvedPlan.planId,scope,approval:{opaque:true},enablement:"apply-explicitly-enabled",protectedEnvironment:"protected-synthetic"};

test("executes one synthetic operation with its fence and requires final zero convergence",async()=>{let mutations=0,verifications=0,fence=0;const r=await executeControlledPlan(request,ports({mutate:async(_kind,_operation,_clientMutationId,fencingToken)=>{mutations++;fence=fencingToken;},verify:async()=>{verifications++;return true;}}));assert.equal(r.status,"success");assert.equal(r.remaining,0);assert.equal(r.outcomes[0]?.outcome,"verified");assert.equal(mutations,1);assert.equal(verifications,1);assert.equal(fence,1);});
test("already converged sends no mutation",async()=>{let mutations=0;const r=await executeControlledPlan(request,ports({inspect:async()=>"already_converged",mutate:async()=>{mutations++;}}));assert.equal(r.status,"success");assert.equal(r.outcomes[0]?.outcome,"already_converged");assert.equal(mutations,0);});
test("missing enablement fails before approval and mutation",async()=>{let approvals=0,mutations=0;const r=await executeControlledPlan({...request,enablement:"dry-run"},ports({verifyApproval:async()=>{approvals++;return claims();},mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-002");assert.equal(approvals,0);assert.equal(mutations,0);});
test("approval mismatch and expiry fail before lease",async()=>{for(const bad of [{...claims(),planId:"0".repeat(64)},{...claims(),expiresAtMs:now-1}]){let leases=0;const r=await executeControlledPlan(request,ports({verifyApproval:async()=>bad,acquireLease:async()=>{leases++;return null;}}));assert.equal(r.status,"error");assert.equal(leases,0);}});
test("protected environment substitution fails before lease",async()=>{let leases=0;const r=await executeControlledPlan(request,ports({verifyApproval:async()=>({...claims(),protectedEnvironment:"protected-other"}),acquireLease:async()=>{leases++;return null;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-003");assert.equal(leases,0);});
test("preflight mismatch does not consume nonce or mutate",async()=>{let nonce=0,mutations=0;const other=plan([operation("relationship.dependency.7.9.add")]);const r=await executeControlledPlan(request,ports({replan:async()=>other,consumeNonce:async()=>{nonce++;return true;},mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-007");assert.equal(nonce,0);assert.equal(mutations,0);});
test("whole-plan budget denial defers before nonce, inspection, or mutation",async()=>{let nonce=0,inspections=0,mutations=0;const r=await executeControlledPlan(request,ports({admit:async kinds=>{assert.deepEqual(kinds,["add_blocked_by"]);return false;},consumeNonce:async()=>{nonce++;return true;},inspect:async()=>{inspections++;return"ready";},mutate:async()=>{mutations++;}}));assert.equal(r.status,"deferred");assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-015");assert.deepEqual(r.outcomes.map(value=>value.outcome),["not_attempted"]);assert.equal(nonce,0);assert.equal(inspections,0);assert.equal(mutations,0);});
test("replayed nonce prevents mutation",async()=>{let mutations=0;const r=await executeControlledPlan(request,ports({consumeNonce:async()=>false,mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-008");assert.equal(mutations,0);});
test("lease loss prevents mutation",async()=>{let checks=0,mutations=0;const r=await executeControlledPlan(request,ports({acquireLease:async()=>({fencingToken:1,valid:async()=>++checks===1,release:async()=>{}}),mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-006");assert.equal(mutations,0);});
test("precondition mismatch records failure and stops",async()=>{let mutations=0;const r=await executeControlledPlan(request,ports({inspect:async()=>"mismatch",mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-009");assert.equal(r.outcomes[0]?.outcome,"failed");assert.equal(mutations,0);});
test("mutation and verification failures are distinct and never retried",async()=>{let attempts=0;const mutation=await executeControlledPlan(request,ports({mutate:async()=>{attempts++;throw new Error("provider secret");}}));assert.equal(attempts,1);assert.equal(mutation.diagnostics[0]?.code,"YKP-APPLY-010");const verification=await executeControlledPlan(request,ports({verify:async()=>false}));assert.equal(verification.diagnostics[0]?.code,"YKP-APPLY-011");});
test("invalidates accepted mutation state before its minimum verification read",async()=>{const order:string[]=[];const outcome=await executeControlledPlan(request,ports({mutate:async()=>{order.push("mutate");},invalidateAfterMutation:async()=>{order.push("invalidate");},verify:async()=>{order.push("verify");return true;},replan:async()=>{order.push("snapshot");return order.filter(value=>value==="snapshot").length===1?approvedPlan:zeroPlan;}}));assert.equal(outcome.status,"success");assert.deepEqual(order,["snapshot","mutate","invalidate","verify","snapshot"]);});
test("invalidation failure stops before verification and final snapshot",async()=>{let verifications=0,replans=0;const outcome=await executeControlledPlan(request,ports({replan:async()=>{replans++;return approvedPlan;},invalidateAfterMutation:async()=>{throw new Error("cache state");},verify:async()=>{verifications++;return true;}}));assert.equal(outcome.diagnostics[0]?.code,"YKP-APPLY-011");assert.equal(verifications,0);assert.equal(replans,1);});
test("preserves stable redacted port failure classes including deferred budget",async()=>{const cases=[["authentication","YKP-APPLY-013","error"],["authorization","YKP-APPLY-014","error"],["deferred_rate_budget","YKP-APPLY-015","deferred"],["provider","YKP-APPLY-016","error"],["invariant","YKP-APPLY-017","error"]] as const;for(const [failureClass,code,status] of cases){const outcome=await executeControlledPlan(request,ports({replan:async()=>{throw new ApplyPortError(failureClass);}}));assert.equal(outcome.status,status);assert.equal(outcome.diagnostics[0]?.code,code);assert.doesNotMatch(JSON.stringify(outcome),/token|provider body|private/u);}});
test("stops after first failure and marks later operations not attempted",async()=>{const first=operation("first"),second=operation("second",["first"]),two=plan([first,second]);let attempts=0,replans=0;const matching={...claims(two),planId:two.planId,operationDigest:hash(two.operations)};const r=await executeControlledPlan({...request,approvedPlanId:two.planId},ports({verifyApproval:async()=>matching,replan:async()=>++replans===1?two:zeroPlan,mutate:async()=>{attempts++;throw new Error("stop");}}));assert.equal(attempts,1);assert.deepEqual(r.outcomes.map(x=>x.outcome),["failed","not_attempted"]);});
test("nonzero final reconciliation fails",async()=>{const r=await executeControlledPlan(request,ports({replan:async()=>approvedPlan}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-012");assert.equal(r.remaining,1);});
test("dependency order is rejected from the fresh plan before nonce or mutation",async()=>{const invalid=plan([operation("second",["missing"])]);let nonce=0,mutations=0;const r=await executeControlledPlan({...request,approvedPlanId:invalid.planId},ports({verifyApproval:async()=>claims(invalid),replan:async()=>invalid,consumeNonce:async()=>{nonce++;return true;},mutate:async()=>{mutations++;}}));assert.equal(r.diagnostics[0]?.code,"YKP-APPLY-007");assert.equal(nonce,0);assert.equal(mutations,0);});
test("public report contains only aggregate outcomes and stable diagnostics",async()=>{const privateResult=await executeControlledPlan(request,ports({mutate:async()=>{throw new Error("https://private.invalid token node-id");}}));const report=renderPublicApplyReport(privateResult);const serialized=JSON.stringify(report);assert.doesNotMatch(serialized,/private|token|node-id|synthetic-nonce|repository:|project:/u);assert.equal(report.counts.failed,1);});
