import test from "node:test";
import { createGitHubRateLedger } from "../src/github-rate-ledger.js";
import assert from "node:assert/strict";
import { Kind, parse } from "graphql";
import { GITHUB_MUTATION_DOCUMENTS, GitHubMutationTransportError, createGitHubMutationTransport, type MutationVariables, type PermissionAttestation } from "../src/github-mutation-transport.js";
const client="a".repeat(64),allKinds=["create_project_field","update_project_field_options","update_project_item_field_value","set_issue_type","add_sub_issue","add_blocked_by"] as const;
function profile(kinds:readonly (typeof allKinds)[number][]):PermissionAttestation{return{projects:kinds.some(kind=>kind.startsWith("create_")||kind.startsWith("update_project_"))?"write":"none",issues:kinds.some(kind=>kind==="set_issue_type"||kind.startsWith("add_"))?"write":"none",extraPermissions:[]};}
const cases=[
 ["create_project_field",{kind:"create_project_field",projectId:"p",dataType:"TEXT",name:"Area"},{projectV2Field:{id:"new-field"}}],
 ["update_project_field_options",{kind:"update_project_field_options",fieldId:"f",observedOptions:[{id:"o",name:"One",color:"BLUE",description:"kept"}],newOption:{name:"Two",color:"GRAY",description:""}},{projectV2Field:{id:"f"}}],
 ["update_project_item_field_value",{kind:"update_project_item_field_value",projectId:"p",itemId:"i",fieldId:"f",value:{number:3}},{projectV2Item:{id:"i"}}],
 ["add_sub_issue",{kind:"add_sub_issue",parentIssueId:"parent",subIssueId:"child"},{issue:{id:"parent"},subIssue:{id:"child"}}],
 ["add_blocked_by",{kind:"add_blocked_by",blockedIssueId:"blocked",blockingIssueId:"blocker"},{issue:{id:"blocked"},blockingIssue:{id:"blocker"}}],
 ["set_issue_type",{kind:"set_issue_type",issueId:"issue",issueTypeId:"type"},{issue:{id:"issue",issueType:{id:"type"}}}]
] as const;
function response(field:string,payload:unknown,status=200,headers:Record<string,string>={}):Response{return new Response(JSON.stringify({data:{[field]:{clientMutationId:client,...(payload as object)}}}),{status,headers:{"content-type":"application/json",...headers}});}
const fields={create_project_field:"createProjectV2Field",update_project_field_options:"updateProjectV2Field",update_project_item_field_value:"updateProjectV2ItemFieldValue",set_issue_type:"updateIssueIssueType",add_sub_issue:"addSubIssue",add_blocked_by:"addBlockedBy"} as const;
test("each document has exactly one named mutation, variable, and top-level field",()=>{for(const [kind] of cases){const ast=parse(GITHUB_MUTATION_DOCUMENTS[kind]),definition=ast.definitions[0];assert.equal(ast.definitions.length,1);assert.equal(definition?.kind,Kind.OPERATION_DEFINITION);if(definition?.kind!==Kind.OPERATION_DEFINITION)throw new Error();assert.equal(definition.operation,"mutation");assert.match(definition.name?.value??"",/^Yukh/u);assert.equal(definition.variableDefinitions?.length,1);assert.equal(definition.selectionSet.selections.length,1);const selection=definition.selectionSet.selections[0];assert.equal(selection?.kind,Kind.FIELD);if(selection?.kind===Kind.FIELD)assert.equal(selection.name.value,fields[kind]);}});
test("all five valid operations use one fixed POST request and validate receipts",async()=>{for(const [kind,variables,payload] of cases){let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async(input,init)=>{calls++;assert.equal(String(input),"https://api.github.com/graphql");assert.equal(init?.method,"POST");assert.equal(init?.redirect,"manual");const sent=JSON.parse(String(init?.body));assert.equal(sent.query,GITHUB_MUTATION_DOCUMENTS[kind]);assert.deepEqual(Object.keys(sent.variables),["input"]);return response(fields[kind],payload);}});const receipt=await transport.execute(kind,variables as MutationVariables,client);assert.equal(receipt.providerAccepted,true);assert.equal(calls,1);}});
test("option append preserves observed metadata and forces neutral new defaults",async()=>{let sent:unknown;const kind="update_project_field_options" as const,transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async(_i,init)=>{sent=JSON.parse(String(init?.body));return response("updateProjectV2Field",{projectV2Field:{id:"f"}});}});await transport.execute(kind,cases[1][1] as MutationVariables,client);const options=((sent as any).variables.input.singleSelectOptions);assert.deepEqual(options,[{id:"o",name:"One",color:"BLUE",description:"kept"},{name:"Two",color:"GRAY",description:""}]);});
test("unknown keys, client IDs, unsupported values, and self relationships fail before fetch",async()=>{const invalid:unknown[]=[{...cases[0][1],extra:true},cases[0][1],{kind:"add_sub_issue",parentIssueId:"same",subIssueId:"same"},{kind:"update_project_item_field_value",projectId:"p",itemId:"i",fieldId:"f",value:{number:1,text:"x"}}];for(let i=0;i<invalid.length;i++){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:profile(allKinds),approvedKinds:allKinds,fetch:async()=>{calls++;throw new Error();}});await assert.rejects(t.execute((invalid[i] as any).kind,invalid[i] as MutationVariables,i===1?"short":client),GitHubMutationTransportError);assert.equal(calls,0);}});
test("permission deltas deny before fetch",async()=>{for(const [kind,variables] of [cases[0],cases[3]]){for(const p of [{projects:"write",issues:"write",extraPermissions:[]},{projects:"read",issues:"read",extraPermissions:["contents:write"]}] as PermissionAttestation[]){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:p,approvedKinds:[kind],fetch:async()=>{calls++;throw new Error();}});await assert.rejects(t.execute(kind,variables as MutationVariables,client),(e:unknown)=>e instanceof GitHubMutationTransportError&&e.code==="YKP-GH-WRITE-003");assert.equal(calls,0);}}});
test("redirect, auth, rate, malformed, GraphQL, client and receipt mismatches are redacted and never retried",async()=>{const kind="add_sub_issue" as const,responses=[new Response(null,{status:302}),new Response("x",{status:401}),new Response("x",{status:429}),new Response("{",{status:200,headers:{"content-type":"application/json"}}),new Response(JSON.stringify({errors:[{message:"private token url"}]}),{status:200,headers:{"content-type":"application/json"}}),new Response(JSON.stringify({data:{addSubIssue:{clientMutationId:"wrong",issue:{id:"parent"},subIssue:{id:"child"}}}}),{status:200,headers:{"content-type":"application/json"}}),response("addSubIssue",{issue:{id:"wrong"},subIssue:{id:"child"}})];for(const synthetic of responses){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async()=>{calls++;return synthetic;}});await assert.rejects(t.execute(kind,cases[3][1] as MutationVariables,client),(e:unknown)=>e instanceof GitHubMutationTransportError&&!/private|token|url|wrong/u.test(String(e)));assert.equal(calls,1);}});

test("shared GraphQL ledger denies mutation before HTTP when its declared reserve is unavailable",async()=>{let calls=0;const kind="add_sub_issue" as const,ledger=createGitHubRateLedger({graphqlRemaining:500}),transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],rateLedger:ledger,fetch:async()=>{calls++;throw new Error("must not run");}});await assert.rejects(transport.execute(kind,cases[3]![1] as MutationVariables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&error.code==="YKP-GH-WRITE-008");assert.equal(calls,0);assert.equal(ledger.snapshot().graphqlRequests,0);});
test("runtime module does not import the AST parser",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../../src/github-mutation-transport.ts",import.meta.url),"utf8"));assert.doesNotMatch(source,/from ["']graphql["']/u);});
