import assert from "node:assert/strict";
import test from "node:test";
import { createGitHubRestSnapshotReadTransport, createRestProjectSnapshotReader, readRestProjectSnapshot } from "../src/github-rest-snapshot.js";
import { GitHubTransportError } from "../src/github-transport.js";
import { createGitHubRateLedger } from "../src/github-rate-ledger.js";

function response(body:unknown,status=200,headers:Record<string,string>={}):Response{return new Response(status===304?null:JSON.stringify(body),{status,headers:{...(status===304?{}:{"content-type":"application/json"}),"x-ratelimit-remaining":"4000",...headers}});}
function fixtures(count:number){const issues=Array.from({length:count},(_,index)=>{const number=index+1;return{id:number,node_id:`I_${number}`,number,body:`<!-- yukh:issue:v1\nschema: 1\nwork_type: task\narea: runtime\n-->`,repository:{full_name:"example/atlas"},parent_issue_url:null,issue_dependencies_summary:{blocked_by:0,blocking:0}};});const items=issues.map(issue=>({id:issue.id+100,node_id:`PVTI_${issue.number}`,content:issue,fields:[{id:10,name:"Priority",data_type:"single_select",value:{id:"p1",name:{raw:"P1"}}}]}));return{issues,items};}
function fetcher(count:number,options:{etag?:boolean;delay?:boolean}={}){const data=fixtures(count);let calls=0;const fetch:typeof globalThis.fetch=async(input,init)=>{calls++;if(options.delay)await new Promise(resolve=>setTimeout(resolve,5));const url=String(input);const headers=init?.headers as Record<string,string>|undefined;if(options.etag&&headers?.["if-none-match"]==="etag-1")return response(null,304,{etag:"etag-1"});if(url.endsWith("/repos/example/atlas"))return response({node_id:"R_1",owner:{type:"Organization"}},200,options.etag?{etag:"etag-1"}:{});if(url.endsWith("/orgs/example/projectsV2/7"))return response({node_id:"P_7",number:7},200,options.etag?{etag:"etag-1"}:{});if(url.includes("/fields?"))return response([{id:10,node_id:"F_10",name:"Priority",data_type:"single_select",options:[{id:"p1",name:{raw:"P1"}}]}],200,options.etag?{etag:"etag-1"}:{});if(url.includes("/items?"))return response(data.items,200,options.etag?{etag:"etag-1"}:{});throw new Error(`unexpected request: ${url}`);};return{fetch,calls:()=>calls};}

for(const count of [1,10,100])test(`builds one REST snapshot for ${count} issues with GraphQL exhausted`,async()=>{const mock=fetcher(count);const snapshot=await readRestProjectSnapshot({ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:Array.from({length:count},(_,i)=>i+1)},{token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0});assert.equal(snapshot.issues.size,count);assert.equal(snapshot.evidence.graphqlRequests,0);assert.equal(snapshot.evidence.restRequests,4);assert.equal(mock.calls(),4);});

for(const count of [1,10,100])test(`asserts the shared run ledger ceiling for ${count} issues`,async()=>{const mock=fetcher(count),ledger=createGitHubRateLedger({restRemaining:504,graphqlRemaining:0,maxRestRequests:5});const snapshot=await readRestProjectSnapshot({ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:Array.from({length:count},(_,i)=>i+1)},{token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0,rateLedger:ledger});assert.equal(snapshot.issues.size,count);assert.equal(mock.calls(),4);assert.deepEqual(ledger.snapshot(),{restRequests:4,graphqlRequests:0,graphqlPoints:0,restRemaining:500,graphqlRemaining:0});assert.equal(ledger.reserve("rest"),false);});

test("coalesces concurrent operation reads into one snapshot",async()=>{const mock=fetcher(1,{delay:true});const transport=createGitHubRestSnapshotReadTransport({token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0});const variables={ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumber:1};await Promise.all([transport.execute("resolve_scope",variables),transport.execute("read_project_fields",variables),transport.execute("read_project_item",variables),transport.execute("read_issue_relationships",variables)]);assert.equal(mock.calls(),4);});

test("revalidates stale entries conditionally and accepts exact 304",async()=>{let now=0;const mock=fetcher(1,{etag:true});const reader=createRestProjectSnapshotReader({token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0,cacheTtlMs:10,now:()=>now});const input={ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:[1]};await reader.read(input);now=20;const second=await reader.read(input);assert.equal(second.issues.size,1);assert.equal(second.evidence.conditionalRequests,4);assert.equal(mock.calls(),8);});

test("targeted invalidation performs minimum verification reads and final snapshot reuses them",async()=>{const mock=fetcher(1),reader=createRestProjectSnapshotReader({token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0}),input={ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:[1]};await reader.read(input);assert.equal(mock.calls(),4);reader.invalidate(input,"item");await reader.read(input);assert.equal(mock.calls(),5);reader.invalidate(input,"schema");await reader.read(input);assert.equal(mock.calls(),7);await reader.read(input);assert.equal(mock.calls(),7);});

test("fails closed before a request when the declared REST budget is too small",async()=>{const mock=fetcher(1);await assert.rejects(readRestProjectSnapshot({ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:[1]},{token:"synthetic-token",fetch:mock.fetch,graphqlRemaining:0,maxRestRequests:3}),(error:unknown)=>error instanceof GitHubTransportError&&error.code==="YKP-RATE-001");assert.equal(mock.calls(),3);});

test("rejects a pagination link whose origin only prefixes the GitHub API origin",async()=>{const base=fetcher(1);const fetch:typeof globalThis.fetch=async(input,init)=>{const result=await base.fetch(input,init);if(String(input).includes("/fields?"))return response(await result.json(),200,{link:'<https://api.github.com.attacker.invalid/orgs/example/projectsV2/7/fields?page=2>; rel="next"'});return result;};await assert.rejects(readRestProjectSnapshot({ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:[1]},{token:"synthetic-token",fetch,graphqlRemaining:0}),(error:unknown)=>error instanceof GitHubTransportError&&error.code==="YKP-CAPABILITY-001");assert.equal(base.calls(),3);});

test("fails closed before the allowlisted relationship query crosses its reserve",async()=>{const base=fetcher(1);const fetch:typeof globalThis.fetch=async(input,init)=>{const result=await base.fetch(input,init);if(String(input).includes("/items?")){const items=await result.json() as Record<string,unknown>[];((items[0]!.content as Record<string,unknown>).issue_dependencies_summary as Record<string,unknown>).blocked_by=1;return response(items);}return result;};await assert.rejects(readRestProjectSnapshot({ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumbers:[1]},{token:"synthetic-token",fetch,graphqlRemaining:500,graphqlReserve:500}),(error:unknown)=>error instanceof GitHubTransportError&&error.code==="YKP-RATE-001");assert.equal(base.calls(),4);});
