import test from "node:test";
import assert from "node:assert/strict";
import { READ_OPERATIONS, readGitHubObservation, type AllowedReadOperation, type ReadOnlyTransport } from "../src/github-readonly.js";
const scope={subjectRef:"installation:synthetic",ownerLogin:"example-labs",repositoryName:"atlas",projectNumber:7,issueNumber:42};
const end={hasNextPage:false,endCursor:null};
const data:Record<AllowedReadOperation,unknown>={resolve_scope:{...scope,repositoryRef:"repo:1",projectRef:"project:1",issueRef:"issue:1"},read_project_fields:{projectRef:"project:1",nodes:[{id:"field:2",name:"Area",kind:"single_select"},{id:"field:1",name:"Status",kind:"single_select"}],pageInfo:end},read_project_item:{projectRef:"project:1",issueRef:"issue:1",itemRef:"item:1",fingerprint:"item-fingerprint",nodes:[{key:"status",value:"Ready"}],pageInfo:end},read_issue_relationships:{repositoryRef:"repo:1",issueRef:"issue:1",nodes:[{issueNumber:42}],parent:[],blocks:[],pageInfo:end}};
function transport(change:Partial<Record<AllowedReadOperation,unknown>>={},calls:AllowedReadOperation[]=[]):ReadOnlyTransport{return{execute:async(op)=>{calls.push(op);return{byteCount:100,data:change[op]??data[op]};}};}
test("uses only fixed operations and creates stable evidence",async()=>{const calls:AllowedReadOperation[]=[];const a=await readGitHubObservation(scope,transport({},calls));const fields=data.read_project_fields as {nodes:unknown[]};const b=await readGitHubObservation(scope,transport({read_project_fields:{...(data.read_project_fields as object),nodes:[...fields.nodes].reverse()}}));assert.deepEqual(calls,READ_OPERATIONS);assert.equal(a.observation?.evidence.fingerprint,b.observation?.evidence.fingerprint);});
test("paginates with advancing cursors",async()=>{const calls:(string|null)[]=[];const t:ReadOnlyTransport={execute:async(op,v)=>{calls.push(v.cursor as string|null);if(op==="read_project_fields"&&v.cursor===null)return{byteCount:10,data:{projectRef:"project:1",nodes:[{id:"field:1",name:"A",kind:"text"}],pageInfo:{hasNextPage:true,endCursor:"next"}}};if(op==="read_project_fields")return{byteCount:10,data:{projectRef:"project:1",nodes:[{id:"field:2",name:"B",kind:"text"}],pageInfo:end}};return{byteCount:10,data:data[op]};}};const r=await readGitHubObservation(scope,t);assert.equal(r.observation?.projectSchema.fields.length,2);assert.equal(r.observation?.evidence.operationCounts.read_project_fields,2);assert.ok(calls.includes("next"));});
test("rejects repeated cursors atomically",async()=>{const t:ReadOnlyTransport={execute:async(op)=>({byteCount:10,data:op==="read_project_fields"?{projectRef:"project:1",nodes:[],pageInfo:{hasNextPage:true,endCursor:"same"}}:data[op]})};const r=await readGitHubObservation(scope,t);assert.equal(r.observation,null);assert.equal(r.diagnostics[0]?.code,"YKP-GH-READ-007");});
test("rejects binding mismatch without disclosure",async()=>{const r=await readGitHubObservation(scope,transport({resolve_scope:{...(data.resolve_scope as object),repositoryName:"private-name"}}));assert.equal(r.diagnostics[0]?.code,"YKP-GH-READ-006");assert.doesNotMatch(JSON.stringify(r),/private-name|repo:1/u);});
test("does not retry or expose thrown provider errors",async()=>{let calls=0;const r=await readGitHubObservation(scope,{execute:async()=>{calls++;throw new Error("token https://private.invalid secret");}});assert.equal(calls,1);assert.equal(r.diagnostics[0]?.code,"YKP-GH-READ-004");assert.doesNotMatch(JSON.stringify(r),/token|private|secret/u);});
test("rejects byte and duplicate identifier boundaries",async()=>{const huge:ReadOnlyTransport={execute:async(op)=>({byteCount:op==="resolve_scope"?2*1024*1024+1:1,data:data[op]})};assert.equal((await readGitHubObservation(scope,huge)).diagnostics[0]?.code,"YKP-GH-READ-005");const duplicate={...(data.read_project_fields as object),nodes:[{id:"field:1",name:"A",kind:"text"},{id:"field:1",name:"B",kind:"text"}]};assert.equal((await readGitHubObservation(scope,transport({read_project_fields:duplicate}))).diagnostics[0]?.code,"YKP-GH-READ-008");});
test("rejects cross-scope and invalid relationship graphs",async()=>{const bad={...(data.read_issue_relationships as object),nodes:[{issueNumber:42}],blocks:[{from:42,to:99}]};assert.equal((await readGitHubObservation(scope,transport({read_issue_relationships:bad}))).diagnostics[0]?.code,"YKP-GH-READ-006");});
test("rejects invalid scope before transport",async()=>{let calls=0;const r=await readGitHubObservation({...scope,issueNumber:0},{execute:async()=>{calls++;throw new Error();}});assert.equal(calls,0);assert.equal(r.diagnostics[0]?.code,"YKP-GH-READ-001");});
test("surface exposes no mutation, URL, document, method, or credential",()=>{assert.deepEqual(READ_OPERATIONS,["resolve_scope","read_project_fields","read_project_item","read_issue_relationships"]);assert.doesNotMatch(JSON.stringify(READ_OPERATIONS),/mutation|url|token|credential|document|method/ui);});
