import assert from "node:assert/strict";
import test from "node:test";
import { createGitHubRateLedger } from "../src/github-rate-ledger.js";

test("reserves REST and GraphQL atomically before crossing run or provider limits",()=>{const ledger=createGitHubRateLedger({restRemaining:503,graphqlRemaining:700,maxRestRequests:2,maxGraphqlRequests:2,maxGraphqlPoints:200});assert.equal(ledger.reserve("rest"),true);assert.equal(ledger.reserve("rest"),true);assert.equal(ledger.reserve("rest"),false);assert.equal(ledger.reserve("graphql",100),true);assert.equal(ledger.reserve("graphql",100),true);assert.equal(ledger.reserve("graphql",1),false);assert.deepEqual(ledger.snapshot(),{restRequests:2,graphqlRequests:2,graphqlPoints:200,restRemaining:501,graphqlRemaining:500,deferredResource:"graphql"});});
test("provider observations only reduce shared remaining state",()=>{const ledger=createGitHubRateLedger({restRemaining:4000,graphqlRemaining:4000});ledger.observe("rest",3500);ledger.observe("rest",3900);ledger.observe("graphql",3200);ledger.observe("graphql",3700);assert.equal(ledger.snapshot().restRemaining,3500);assert.equal(ledger.snapshot().graphqlRemaining,3200);});
test("invalid observations and costs fail closed without consuming a request",()=>{const ledger=createGitHubRateLedger();ledger.observe("rest",Number.NaN);assert.equal(ledger.reserve("rest",0),false);assert.equal(ledger.reserve("graphql",501),false);assert.equal(ledger.snapshot().restRequests,0);assert.equal(ledger.snapshot().graphqlRequests,0);});
test("whole-plan admission is atomic and non-consuming",()=>{const ledger=createGitHubRateLedger({restRemaining:1001,graphqlRemaining:1300,restReserve:1000,graphqlReserve:1000,maxRestRequests:1,maxGraphqlRequests:3,maxGraphqlPoints:300});assert.equal(ledger.admit([{resource:"rest",cost:1},{resource:"graphql",cost:100},{resource:"graphql",cost:100},{resource:"graphql",cost:100}]),true);assert.deepEqual(ledger.snapshot(),{restRequests:0,graphqlRequests:0,graphqlPoints:0,restRemaining:1001,graphqlRemaining:1300,deferredResource:null});});
test("whole-plan admission defers before consuming any partial budget",()=>{const ledger=createGitHubRateLedger({restRemaining:1001,graphqlRemaining:1299,restReserve:1000,graphqlReserve:1000,maxRestRequests:1,maxGraphqlRequests:3,maxGraphqlPoints:300});assert.equal(ledger.admit([{resource:"rest",cost:1},{resource:"graphql",cost:100},{resource:"graphql",cost:100},{resource:"graphql",cost:100}]),false);assert.deepEqual(ledger.snapshot(),{restRequests:0,graphqlRequests:0,graphqlPoints:0,restRemaining:1001,graphqlRemaining:1299,deferredResource:"graphql"});});
test("defaults enforce the accepted limits and reserves cannot be lowered",()=>{const ledger=createGitHubRateLedger();for(let index=0;index<32;index++)assert.equal(ledger.reserve("rest"),true);assert.equal(ledger.reserve("rest"),false);assert.equal(ledger.reserve("graphql",100),true);assert.equal(ledger.reserve("graphql",1),false);assert.throws(()=>createGitHubRateLedger({restReserve:499}));assert.throws(()=>createGitHubRateLedger({graphqlReserve:499}));assert.throws(()=>createGitHubRateLedger({maxRestRequests:65}));assert.throws(()=>createGitHubRateLedger({maxGraphqlRequests:5}));});
