import test from "node:test";
import assert from "node:assert/strict";
import { GITHUB_READ_QUERY_DOCUMENTS, GitHubTransportError, createGitHubGraphQLReadTransport } from "../src/github-transport.js";

function json(data:unknown,status=200,headers:Record<string,string>={}):Response{return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json",...headers}});}
test("documents are fixed named queries with no mutation surface",()=>{assert.equal(Object.keys(GITHUB_READ_QUERY_DOCUMENTS).length,4);for(const document of Object.values(GITHUB_READ_QUERY_DOCUMENTS)){assert.match(document,/^query Yukh/u);assert.doesNotMatch(document,/\bmutation\b|\bsubscription\b/u);}});
test("field query includes bounded option and iteration metadata",()=>{const document=GITHUB_READ_QUERY_DOCUMENTS.read_project_fields;assert.match(document,/ProjectV2SingleSelectField/u);assert.match(document,/options\{id name\}/u);assert.match(document,/completedIterations/u);});
test("uses fixed endpoint, POST, redirect rejection, and one request",async()=>{let calls=0;let seenUrl="",seenInit:RequestInit|undefined;const fetch:typeof globalThis.fetch=async(input,init)=>{calls++;seenUrl=String(input);seenInit=init;return json({data:{repository:{id:"r",issue:{id:"i",number:2,body:"synthetic body",projectItems:{nodes:[],pageInfo:{hasNextPage:false}}}},repositoryOwner:{projectV2:{id:"p",number:5}}}});};const t=createGitHubGraphQLReadTransport({token:"synthetic-token",fetch});const result=await t.execute("resolve_scope",{ownerLogin:"example",repositoryName:"atlas",projectNumber:5,issueNumber:2});assert.equal(calls,1);assert.equal(seenUrl,"https://api.github.com/graphql");assert.equal(seenInit?.method,"POST");assert.equal(seenInit?.redirect,"manual");assert.match(String(seenInit?.body),/YukhResolveScope/u);assert.match(String(seenInit?.body),/\bbody\b/u);assert.equal((result.data as Record<string,unknown>).issueBody,"synthetic body");});
test("classifies authentication and rate limiting without provider content",async()=>{for(const [status,headers,code] of [[401,{},"YKP-GH-READ-002"],[403,{"x-ratelimit-remaining":"0"},"YKP-GH-READ-009"],[429,{},"YKP-GH-READ-009"]] as const){const t=createGitHubGraphQLReadTransport({token:"secret",fetch:async()=>new Response("private provider token",{status,headers})});await assert.rejects(t.execute("resolve_scope",{}),(e:unknown)=>e instanceof GitHubTransportError&&e.code===code&&!String(e).includes("private"));}});
test("rejects redirects, non-json, malformed, and oversized responses",async()=>{const cases=[new Response(null,{status:302,headers:{location:"https://private.invalid"}}),new Response("html",{status:200,headers:{"content-type":"text/html"}}),new Response("{",{status:200,headers:{"content-type":"application/json"}}),new Response(new Uint8Array(2*1024*1024+1),{status:200,headers:{"content-type":"application/json"}})];for(const response of cases){const t=createGitHubGraphQLReadTransport({token:"secret",fetch:async()=>response});await assert.rejects(t.execute("resolve_scope",{}),GitHubTransportError);}});
test("rejects missing and oversized issue bodies without disclosure",async()=>{for(const body of [null,"private".repeat(50000)]){const t=createGitHubGraphQLReadTransport({token:"secret",fetch:async()=>json({data:{repository:{id:"r",issue:{id:"i",number:2,body,projectItems:{nodes:[],pageInfo:{hasNextPage:false}}}},repositoryOwner:{projectV2:{id:"p",number:5}}}})});await assert.rejects(t.execute("resolve_scope",{ownerLogin:"example",repositoryName:"atlas",projectNumber:5,issueNumber:2}),(e:unknown)=>e instanceof GitHubTransportError&&!String(e).includes("private"));}});
test("constructor rejects empty or control-bearing credentials",()=>{assert.throws(()=>createGitHubGraphQLReadTransport({token:""}));assert.throws(()=>createGitHubGraphQLReadTransport({token:"bad\nvalue"}));});
