import test from "node:test";
import { createGitHubRateLedger } from "../src/github-rate-ledger.js";
import assert from "node:assert/strict";
import { Kind, parse } from "graphql";
import { GITHUB_MUTATION_DOCUMENTS, GitHubMutationTransportError, createGitHubMutationTransport, type MutationVariables, type PermissionAttestation } from "../src/github-mutation-transport.js";
const client="a".repeat(64),allKinds=["create_project_field","update_project_field_options","update_project_item_field_value","set_issue_type","add_sub_issue","add_blocked_by"] as const;
function profile(kinds:readonly (typeof allKinds)[number][]):PermissionAttestation{return{projects:kinds.some(kind=>kind.startsWith("create_")||kind.startsWith("update_project_"))?"write":"none",issues:kinds.some(kind=>kind==="set_issue_type"||kind.startsWith("add_"))?"write":"none",extraPermissions:[]};}
const cases=[
 ["create_project_field",{kind:"create_project_field",ownerKind:"orgs",ownerLogin:"example",projectNumber:7,dataType:"TEXT",name:"Area"},{projectV2Field:{id:"new-field"}}],
 ["update_project_field_options",{kind:"update_project_field_options",fieldId:"f",observedOptions:[{id:"o",name:"One",color:"BLUE",description:"kept"}],newOption:{name:"Two",color:"GRAY",description:""}},{projectV2Field:{id:"f"}}],
 ["update_project_item_field_value",{kind:"update_project_item_field_value",projectId:"p",itemId:"i",fieldId:"f",value:{number:3}},{projectV2Item:{id:"i"}}],
 ["add_sub_issue",{kind:"add_sub_issue",parentIssueId:"parent",subIssueId:"child"},{issue:{id:"parent"},subIssue:{id:"child"}}],
 ["add_blocked_by",{kind:"add_blocked_by",blockedIssueId:"blocked",blockingIssueId:"blocker"},{issue:{id:"blocked"},blockingIssue:{id:"blocker"}}],
 ["set_issue_type",{kind:"set_issue_type",ownerLogin:"example",repositoryName:"atlas",issueNumber:27,issueTypeName:"Gate"},{}]
] as const;
function response(field:string,payload:unknown,status=200,headers:Record<string,string>={}):Response{return new Response(JSON.stringify({data:{[field]:{clientMutationId:client,...(payload as object)}}}),{status,headers:{"content-type":"application/json",...headers}});}
const fields={create_project_field:"createProjectV2Field",update_project_field_options:"updateProjectV2Field",update_project_item_field_value:"updateProjectV2ItemFieldValue",set_issue_type:"updateIssueIssueType",add_sub_issue:"addSubIssue",add_blocked_by:"addBlockedBy"} as const;
test("each GraphQL document has exactly one named mutation, variable, and top-level field",()=>{for(const [kind] of cases){if(kind==="create_project_field"||kind==="set_issue_type")continue;const ast=parse(GITHUB_MUTATION_DOCUMENTS[kind]),definition=ast.definitions[0];assert.equal(ast.definitions.length,1);assert.equal(definition?.kind,Kind.OPERATION_DEFINITION);if(definition?.kind!==Kind.OPERATION_DEFINITION)throw new Error();assert.equal(definition.operation,"mutation");assert.match(definition.name?.value??"",/^Yukh/u);assert.equal(definition.variableDefinitions?.length,1);assert.equal(definition.selectionSet.selections.length,1);const selection=definition.selectionSet.selections[0];assert.equal(selection?.kind,Kind.FIELD);if(selection?.kind===Kind.FIELD)assert.equal(selection.name.value,fields[kind]);}});
test("REST mutation kinds have no GraphQL document or fallback",()=>{for(const kind of ["create_project_field","set_issue_type"])assert.equal(Object.hasOwn(GITHUB_MUTATION_DOCUMENTS,kind),false);assert.doesNotMatch(JSON.stringify(GITHUB_MUTATION_DOCUMENTS),/createProjectV2Field|updateIssueIssueType|YukhCreateProjectField|YukhSetIssueType/u);});
test("all valid operations use one fixed request and validate receipts",async()=>{for(const [kind,variables,payload] of cases){let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async(input,init)=>{calls++;assert.equal(init?.redirect,"manual");const sent=JSON.parse(String(init?.body));if(kind==="create_project_field"){assert.equal(init?.method,"POST");assert.equal(String(input),"https://api.github.com/orgs/example/projectsV2/7/fields");assert.equal((init?.headers as Record<string,string>)["x-github-api-version"],"2026-03-10");assert.deepEqual(sent,{name:"Area",data_type:"text"});return new Response(JSON.stringify({node_id:"synthetic-field",name:"Area",data_type:"text"}),{status:201,headers:{"content-type":"application/json"}});}if(kind==="set_issue_type"){assert.equal(init?.method,"PATCH");assert.equal(String(input),"https://api.github.com/repos/example/atlas/issues/27");assert.equal((init?.headers as Record<string,string>)["x-github-api-version"],"2026-03-10");assert.deepEqual(sent,{type:"Gate"});return new Response(JSON.stringify({number:27,type:{name:"Gate"}}),{status:200,headers:{"content-type":"application/json"}});}assert.equal(init?.method,"POST");assert.equal(String(input),"https://api.github.com/graphql");assert.equal(sent.query,GITHUB_MUTATION_DOCUMENTS[kind]);assert.deepEqual(Object.keys(sent.variables),["input"]);return response(fields[kind],payload);}});const receipt=await transport.execute(kind,variables as MutationVariables,client);assert.equal(receipt.providerAccepted,true);assert.equal(calls,1);}});
test("option append preserves observed metadata and forces neutral new defaults",async()=>{let sent:unknown;const kind="update_project_field_options" as const,transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async(_i,init)=>{sent=JSON.parse(String(init?.body));return response("updateProjectV2Field",{projectV2Field:{id:"f"}});}});await transport.execute(kind,cases[1][1] as MutationVariables,client);const options=((sent as any).variables.input.singleSelectOptions);assert.deepEqual(options,[{id:"o",name:"One",color:"BLUE",description:"kept"},{name:"Two",color:"GRAY",description:""}]);});
test("single-select field creation uses REST with the exact nine-option contract and zero GraphQL budget",async()=>{const names=["Governance","Security","Architecture","Runtime","Provider","Audit","Delivery","Documentation","Release"],options=names.map(name=>({name,color:"GRAY" as const,description:""})),ledger=createGitHubRateLedger({restRemaining:1000,graphqlRemaining:0}),kind="create_project_field" as const;let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],rateLedger:ledger,fetch:async(input,init)=>{calls++;assert.equal(String(input),"https://api.github.com/users/example/projectsV2/5/fields");assert.doesNotMatch(String(input),/graphql/u);const sent=JSON.parse(String(init?.body));assert.deepEqual(sent,{name:"Area",data_type:"single_select",single_select_options:options});return new Response(JSON.stringify({node_id:"synthetic-area",name:"Area",data_type:"single_select",options:options.map(option=>({name:{raw:option.name},color:option.color,description:{raw:option.description}}))}),{status:201,headers:{"content-type":"application/json","x-ratelimit-remaining":"998"}});}});const receipt=await transport.execute(kind,{kind,ownerKind:"users",ownerLogin:"example",projectNumber:5,dataType:"SINGLE_SELECT",name:"Area",options},client);assert.equal(receipt.providerAccepted,true);assert.equal(calls,1);assert.deepEqual(ledger.snapshot(),{restRequests:1,graphqlRequests:0,graphqlPoints:0,restRemaining:998,graphqlRemaining:0});});
test("Issue Type update consumes one REST request with GraphQL exhausted",async()=>{const kind="set_issue_type" as const,ledger=createGitHubRateLedger({restRemaining:1000,graphqlRemaining:0});let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],rateLedger:ledger,fetch:async input=>{calls++;assert.doesNotMatch(String(input),/graphql/u);return new Response(JSON.stringify({number:27,type:{name:"Gate"}}),{status:200,headers:{"content-type":"application/json","x-ratelimit-remaining":"998"}});}});await transport.execute(kind,{kind,ownerLogin:"example",repositoryName:"atlas",issueNumber:27,issueTypeName:"Gate"},client);assert.equal(calls,1);assert.deepEqual(ledger.snapshot(),{restRequests:1,graphqlRequests:0,graphqlPoints:0,restRemaining:998,graphqlRemaining:0});});
test("REST create rejects invalid bindings before HTTP and never falls back to GraphQL",async()=>{const kind="create_project_field" as const;for(const variables of [{kind,ownerKind:"users",ownerLogin:"bad/name",projectNumber:5,dataType:"TEXT",name:"Area"},{kind,ownerKind:"users",ownerLogin:"example",projectNumber:0,dataType:"TEXT",name:"Area"}] as unknown as MutationVariables[]){let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async()=>{calls++;throw new Error("must not run");}});await assert.rejects(transport.execute(kind,variables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&error.code==="YKP-GH-WRITE-001");assert.equal(calls,0);}});
test("REST create classifies validation and receipt failures without body disclosure or retry",async()=>{const kind="create_project_field" as const,variables=cases[0][1] as MutationVariables,secret="private provider token url";for(const fixture of [new Response(JSON.stringify({message:secret}),{status:422,headers:{"content-type":"application/json"}}),new Response(JSON.stringify({node_id:"field",name:"Wrong",data_type:"text",message:secret}),{status:201,headers:{"content-type":"application/json"}})]){let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async()=>{calls++;return fixture;}});await assert.rejects(transport.execute(kind,variables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&!String(error).includes(secret));assert.equal(calls,1);}});
test("REST create preserves stable auth, rate, redirect, malformed, and response-limit classes",async()=>{const kind="create_project_field" as const,variables=cases[0][1] as MutationVariables,fixtures:[[Response,string],[Response,string],[Response,string],[Response,string],[Response,string],[Response,string]]=[[new Response("",{status:401}),"YKP-GH-WRITE-006"],[new Response("",{status:403}),"YKP-GH-WRITE-007"],[new Response("",{status:429}),"YKP-GH-WRITE-008"],[new Response("",{status:302}),"YKP-GH-WRITE-005"],[new Response("{",{status:201,headers:{"content-type":"application/json"}}),"YKP-GH-WRITE-009"],[new Response(`{"padding":"${"x".repeat(2*1024*1024)}"}`,{status:201,headers:{"content-type":"application/json"}}),"YKP-GH-WRITE-010"]];for(const [fixture,code] of fixtures){let calls=0;const transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async()=>{calls++;return fixture;}});await assert.rejects(transport.execute(kind,variables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&error.code===code);assert.equal(calls,1);}});
test("unknown keys, client IDs, unsupported values, and self relationships fail before fetch",async()=>{const invalid:unknown[]=[{...cases[0][1],extra:true},cases[0][1],{kind:"add_sub_issue",parentIssueId:"same",subIssueId:"same"},{kind:"update_project_item_field_value",projectId:"p",itemId:"i",fieldId:"f",value:{number:1,text:"x"}}];for(let i=0;i<invalid.length;i++){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:profile(allKinds),approvedKinds:allKinds,fetch:async()=>{calls++;throw new Error();}});await assert.rejects(t.execute((invalid[i] as any).kind,invalid[i] as MutationVariables,i===1?"short":client),GitHubMutationTransportError);assert.equal(calls,0);}});
test("permission deltas deny before fetch",async()=>{for(const [kind,variables] of [cases[0],cases[3]]){for(const p of [{projects:"write",issues:"write",extraPermissions:[]},{projects:"read",issues:"read",extraPermissions:["contents:write"]}] as PermissionAttestation[]){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:p,approvedKinds:[kind],fetch:async()=>{calls++;throw new Error();}});await assert.rejects(t.execute(kind,variables as MutationVariables,client),(e:unknown)=>e instanceof GitHubMutationTransportError&&e.code==="YKP-GH-WRITE-003");assert.equal(calls,0);}}});
test("redirect, auth, rate, malformed, GraphQL, client and receipt mismatches are redacted and never retried",async()=>{const kind="add_sub_issue" as const,responses=[new Response(null,{status:302}),new Response("x",{status:401}),new Response("x",{status:429}),new Response("{",{status:200,headers:{"content-type":"application/json"}}),new Response(JSON.stringify({errors:[{message:"private token url"}]}),{status:200,headers:{"content-type":"application/json"}}),new Response(JSON.stringify({data:{addSubIssue:{clientMutationId:"wrong",issue:{id:"parent"},subIssue:{id:"child"}}}}),{status:200,headers:{"content-type":"application/json"}}),response("addSubIssue",{issue:{id:"wrong"},subIssue:{id:"child"}})];for(const synthetic of responses){let calls=0;const t=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],fetch:async()=>{calls++;return synthetic;}});await assert.rejects(t.execute(kind,cases[3][1] as MutationVariables,client),(e:unknown)=>e instanceof GitHubMutationTransportError&&!/private|token|url|wrong/u.test(String(e)));assert.equal(calls,1);}});

test("shared GraphQL ledger denies mutation before HTTP when its declared reserve is unavailable",async()=>{let calls=0;const kind="add_sub_issue" as const,ledger=createGitHubRateLedger({graphqlRemaining:500}),transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],rateLedger:ledger,fetch:async()=>{calls++;throw new Error("must not run");}});await assert.rejects(transport.execute(kind,cases[3]![1] as MutationVariables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&error.code==="YKP-GH-WRITE-008");assert.equal(calls,0);assert.equal(ledger.snapshot().graphqlRequests,0);});
test("shared REST ledger denies field creation before HTTP when its reserve is unavailable",async()=>{let calls=0;const kind="create_project_field" as const,ledger=createGitHubRateLedger({restRemaining:500,graphqlRemaining:0}),transport=createGitHubMutationTransport({token:"synthetic",permissions:profile([kind]),approvedKinds:[kind],rateLedger:ledger,fetch:async()=>{calls++;throw new Error("must not run");}});await assert.rejects(transport.execute(kind,cases[0]![1] as MutationVariables,client),(error:unknown)=>error instanceof GitHubMutationTransportError&&error.code==="YKP-GH-WRITE-008");assert.equal(calls,0);assert.deepEqual(ledger.snapshot(),{restRequests:0,graphqlRequests:0,graphqlPoints:0,restRemaining:500,graphqlRemaining:0});});
test("runtime module does not import the AST parser",async()=>{const source=await import("node:fs/promises").then(fs=>fs.readFile(new URL("../../src/github-mutation-transport.ts",import.meta.url),"utf8"));assert.doesNotMatch(source,/from ["']graphql["']/u);});
