import assert from "node:assert/strict";
import { createHash, createPublicKey, generateKeyPairSync, verify } from "node:crypto";
import test from "node:test";
import { parseProtectedHostCapsule } from "../src/protected-host-capsule.js";

const now=1_800_000_000_000,binding={scope:{ownerLogin:"example",repositoryName:"atlas",projectNumber:7,issueNumber:11},environment:"protected-synthetic"};
function canonical(value:unknown):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}
function fixture(){const pair=generateKeyPairSync("ec",{namedCurve:"P-256"}),jwk=pair.privateKey.export({format:"jwk"}),value={allowed_issuer_refs:["approver:synthetic"],approved_kinds:["update_project_item_field_value"],coordination:{base_uri:"https://coordination.invalid",credential:"synthetic-session-credential",dpop_private_jwk:jwk,epoch:7},enablement:"apply-explicitly-enabled",expires_at_ms:now+60_000,holder_digest:"d".repeat(64),issued_at_ms:now-1000,permissions:{extra_permissions:[],issues:"none",projects:"write"},rate:{graphql_remaining:1000,graphql_reserve:500,max_graphql_points:100,max_graphql_requests:1,max_rest_requests:16,rest_remaining:1000,rest_reserve:500},schema:1,scope:{environment:binding.environment,issue_number:11,owner:"example",project_number:7,repository:"atlas"},version:"protected-host-capsule-v1"};return{source:canonical(value),pair,value};}

test("capsule binds host policy and emits fresh verifiable DPoP proofs",async()=>{const{source,pair}=fixture();let sequence=0;const runtime=parseProtectedHostCapsule(source,binding,{nowMs:()=>now,jti:()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,"0")}`}),authenticate=runtime.options.coordination.authenticate,first=await authenticate({method:"POST",targetUri:"https://coordination.invalid/coordination-primitives/v1/nonces:consume",signal:new AbortController().signal}),second=await authenticate({method:"POST",targetUri:"https://coordination.invalid/coordination-primitives/v1/nonces:consume",signal:new AbortController().signal});assert.equal(first.credential,"synthetic-session-credential");assert.notEqual(first.proof,second.proof);const[header,payload,signature]=first.proof.split(".");assert.ok(header&&payload&&signature);assert.equal(verify("sha256",Buffer.from(`${header}.${payload}`),{key:createPublicKey(pair.privateKey),dsaEncoding:"ieee-p1363"},Buffer.from(signature,"base64url")),true);const claims=JSON.parse(Buffer.from(payload,"base64url").toString());assert.equal(claims.ath,createHash("sha256").update(first.credential).digest("base64url"));assert.equal(claims.htu,"https://coordination.invalid/coordination-primitives/v1/nonces:consume");});

test("capsule rejects noncanonical, stale, mismatched and unknown authority",()=>{const{source,value}=fixture();assert.throws(()=>parseProtectedHostCapsule(`${source}\n`,binding,{nowMs:()=>now}),/invalid host capsule/u);assert.throws(()=>parseProtectedHostCapsule(source,{...binding,environment:"other"},{nowMs:()=>now}),/invalid host capsule/u);assert.throws(()=>parseProtectedHostCapsule(canonical({...value,expires_at_ms:now-1}),binding,{nowMs:()=>now}),/invalid host capsule/u);assert.throws(()=>parseProtectedHostCapsule(canonical({...value,unexpected:true}),binding,{nowMs:()=>now}),/invalid host capsule/u);assert.doesNotMatch(String(assert.throws(()=>parseProtectedHostCapsule("{}",binding,{nowMs:()=>now}))),/credential|private|coordination\.invalid/u);});
