import test from "node:test";
import assert from "node:assert/strict";
import { publishCandidate, type PublicationPort } from "../src/protected-publisher.js";

const candidate={version:"1.2.3",commit:"a".repeat(40),tag:"v1.2.3",assets:["yukh-projects-action-1.2.3.js","yukh-projects-cli-1.2.3.js","yukh-projects-action-1.2.3.yml","yukh-projects-lock-1.2.3.json","yukh-projects-1.2.3.spdx.json","yukh-projects-1.2.3.sha256"]};
function synthetic(overrides:Partial<PublicationPort>={}){let tag:string|undefined,release:string|undefined;const calls:string[]=[];const port:PublicationPort={tagTarget:async()=>tag,releaseForTag:async()=>release,createTag:async(_tag,commit)=>{calls.push("create-tag");tag=commit;},createRelease:async()=>{calls.push("create-release");release="synthetic-release";return release;},...overrides};return{port,calls};}
test("publishes once in tag, verify, release, verify order",async()=>{const fixture=synthetic();const receipt=await publishCandidate(candidate,fixture.port);assert.deepEqual(fixture.calls,["create-tag","create-release"]);assert.equal(receipt.releaseId,"synthetic-release");});
test("rejects malformed candidates before ports",async()=>{for(const value of [{...candidate,version:"v1.2.3"},{...candidate,commit:"short"},{...candidate,tag:"v9.9.9"},{...candidate,assets:candidate.assets.slice(1)}]){let touched=false;const fixture=synthetic({tagTarget:async()=>{touched=true;return undefined;}});await assert.rejects(publishCandidate(value,fixture.port));assert.equal(touched,false);}});
test("existing state prevents mutation",async()=>{for(const overrides of [{tagTarget:async()=>candidate.commit},{releaseForTag:async()=>"existing"}]){const fixture=synthetic(overrides);await assert.rejects(publishCandidate(candidate,fixture.port));assert.deepEqual(fixture.calls,[]);}});
test("receipt mismatches stop without retry",async()=>{const tagMismatch=synthetic({createTag:async()=>{tagMismatch.calls.push("create-tag");}});await assert.rejects(publishCandidate(candidate,tagMismatch.port),/tag receipt/u);assert.deepEqual(tagMismatch.calls,["create-tag"]);let reads=0;const releaseMismatch=synthetic({releaseForTag:async()=>{reads+=1;return undefined;}});await assert.rejects(publishCandidate(candidate,releaseMismatch.port),/release receipt/u);assert.deepEqual(releaseMismatch.calls,["create-tag","create-release"]);assert.equal(reads,2);});
