import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Release Please is recoverable, versions release notes, and cannot publish directly",async()=>{const workflow=await readFile(".github/workflows/release-please.yml","utf8"),config=JSON.parse(await readFile("release-please-config.json","utf8")),notes=await readFile("RELEASE_NOTES.md","utf8");assert.match(workflow,/workflow_dispatch:/u);assert.match(workflow,/release-please-action@[0-9a-f]{40}/u);assert.match(workflow,/skip-github-release: true/u);for(const path of [".release-please-manifest.json","CHANGELOG.md","RELEASE_NOTES.md","package.json","package-lock.json"])assert.match(workflow,new RegExp(`      - ${path.replace(".","\\.")}`,"u"));assert.equal(config["skip-github-release"],true);assert.equal(config["include-component-in-tag"],false);assert.equal(config["include-v-in-tag"],true);assert.ok(!("last-release-sha" in config));assert.deepEqual(config.packages["."]["extra-files"],[{type:"generic",path:"RELEASE_NOTES.md"}]);assert.match(notes,/x-release-please-version/u);assert.doesNotMatch(workflow,/id-token|attestations|packages: write/u);});
test("the v1.7.0 qualification remains immutable while notes describe only v1.8.0",async()=>{const evidence=await readFile("docs/validation/release-1.7.0-provider-parity.md","utf8"),notes=await readFile("RELEASE_NOTES.md","utf8");for(const marker of ["71784218366805922e5a12903eef9073f715f59f","release `v1.7.0`","GraphQL remaining zero","No fresh `v1.7.0` consumer plan ID"])assert.ok(evidence.includes(marker),marker);for(const marker of ["runMcpEffectBControlledApplyV1","root-only export map","publication: disabled","`v1.7.0` at `71784218366805922e5a12903eef9073f715f59f`"])assert.ok(notes.includes(marker),marker);for(const stale of ["add dry-run Action, CLI, and protected releases","align Release Please with v1.3.4 baseline","restores exact parity between single-issue legacy shadow"])assert.ok(!notes.includes(stale),stale);});
test("the v1.3.5 baseline and notes contract contain only the post-v1.3.4 delta",async()=>{const evidence=await readFile("docs/validation/release-1.3.5-baseline.md","utf8"),changelog=await readFile("CHANGELOG.md","utf8");for(const marker of ["21731941c96525802ee1e31c6df9e888ceab07e7","04a6019e40633fa60cb218548579f02f2e26e880","e9b564c767e89e406047f6c99ad4739d01e61ca5","de964d9bf1294d32a2d0f2e0714736efd2d33310","#100","#104","#103","REST-first field creation","zero GraphQL","user-owned","organization-owned","rollback pin"])assert.ok(evidence.includes(marker),marker);for(const marker of ["04a6019e40633fa60cb218548579f02f2e26e880","e9b564c767e89e406047f6c99ad4739d01e61ca5","de964d9bf1294d32a2d0f2e0714736efd2d33310"])assert.equal(changelog.split(marker).length-1,1,marker);assert.doesNotMatch(changelog,/compare\/yukh-projects-v/u);});

test("release preflight is secret-free and emits only read-only evidence",async()=>{const workflow=await readFile(".github/workflows/release-preflight.yml","utf8");assert.match(workflow,/permissions:\n  contents: read/u);assert.match(workflow,/RELEASE_COMMIT: \$\{\{ github\.sha \}\}/u);assert.match(workflow,/npm ci --ignore-scripts/u);assert.match(workflow,/assemble-release-assets\.mjs/u);assert.match(workflow,/release-manifest\.json/u);assert.match(workflow,/retention-days: 1/u);for(const token of ["GITHUB_TOKEN","GH_TOKEN","RELEASE_TOKEN","ACTIONS_ID_TOKEN_REQUEST_URL","ACTIONS_ID_TOKEN_REQUEST_TOKEN"])assert.match(workflow,new RegExp(`test -z "\\$\\{${token}:-\\}"`,"u"),token);assert.doesNotMatch(workflow,/secrets\.|contents: write|id-token: write|attestations: write|npm publish|git tag|publish-release\.mjs/u);});

test("publication requires authenticated authorization before any write permission",async()=>{const workflow=await readFile(".github/workflows/publish-release.yml","utf8");assert.match(workflow,/workflow_dispatch:\n    inputs:\n      authorization-comment-id:/u);assert.doesNotMatch(workflow,/\n  push:|secrets\.|npm publish/u);assert.match(workflow,/permissions: \{\}/u);assert.match(workflow,/jobs:\n  authorize:/u);assert.match(workflow,/issues: read\n      pull-requests: read/u);assert.match(workflow,/verify-release-authorization\.mjs/u);assert.match(workflow,/needs: authorize/u);assert.match(workflow,/needs: \[authorize, preflight\]/u);assert.match(workflow,/environment: release/u);assert.equal(workflow.match(/contents: write/gu)?.length,1);assert.equal(workflow.match(/id-token: write/gu)?.length,1);assert.equal(workflow.match(/attestations: write/gu)?.length,1);assert.equal(workflow.match(/contents: read/gu)?.length,2);const publish=workflow.slice(workflow.indexOf("  publish:"));assert.doesNotMatch(publish,/actions\/checkout|actions\/setup-node|npm ci|npm test|scripts\/[A-Za-z0-9_.-]+\.mjs/u);assert.match(publish,/GH_TOKEN: \$\{\{ github\.token \}\}/u);assert.match(publish,/attest-build-provenance@[0-9a-f]{40}/u);assert.match(publish,/subject-path: release-input\/assets\/yukh-projects-\*/u);});

test("preflight receives exact authorized bindings without publication credentials",async()=>{const workflow=await readFile(".github/workflows/publish-release.yml","utf8"),preflight=workflow.slice(workflow.indexOf("  preflight:"),workflow.indexOf("  publish:"));assert.match(preflight,/ref: \$\{\{ needs\.authorize\.outputs\.release_commit \}\}/u);assert.match(preflight,/git rev-parse 'HEAD\^\{tree\}'/u);assert.match(preflight,/npm ci --ignore-scripts/u);assert.match(preflight,/assemble-release-assets\.mjs/u);assert.match(preflight,/verify-publish-input\.mjs/u);assert.doesNotMatch(preflight,/contents: write|github\.token|secrets\.|\n\s+RELEASE_TOKEN:\s|\n\s+IMMUTABLE_RELEASES_READ_TOKEN:\s|id-token|attestations/u);});

test("publication fails closed on substitution, rerun, and partial release state",async()=>{const workflow=await readFile(".github/workflows/publish-release.yml","utf8"),publish=workflow.slice(workflow.indexOf("  publish:"));for(const marker of ["authorizationBodySha256","workflowBlobSha","assetManifestSha256","checksumIndexSha256","branch.commit?.sha","commit.tree?.sha","workflow.sha","policy.enabled","tagResponse.status!==404","release.tag_name===receipt.tag","created_at!==comment.updated_at","uploaded.digest!==`sha256:${asset.sha256}`","finalRelease.immutable!==true","finalTag.object?.sha!==receipt.releaseCommit"])assert.ok(publish.includes(marker),marker);assert.match(publish,/release rerun or partial state detected/u);assert.match(publish,/draft:true/u);assert.match(publish,/JSON\.stringify\(\{draft:false\}\)/u);assert.doesNotMatch(publish,/setTimeout|retry|sleep|generate_release_notes|git\/refs.*method:"POST"/u);});

test("consumer-neutrality policy supports read-only manual recovery",async()=>{const workflow=await readFile(".github/workflows/policy.yml","utf8");assert.match(workflow,/workflow_dispatch:/u);assert.match(workflow,/permissions:\n  contents: read/u);assert.doesNotMatch(workflow,/contents: write|pull-requests: write|id-token: write/u);});
