import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Release Please is recoverable, versions release notes, and cannot publish directly",async()=>{const workflow=await readFile(".github/workflows/release-please.yml","utf8"),config=JSON.parse(await readFile("release-please-config.json","utf8")),notes=await readFile("RELEASE_NOTES.md","utf8");assert.match(workflow,/workflow_dispatch:/u);assert.match(workflow,/release-please-action@[0-9a-f]{40}/u);assert.match(workflow,/skip-github-release: true/u);assert.equal(config["skip-github-release"],true);assert.equal(config["include-component-in-tag"],false);assert.equal(config["include-v-in-tag"],true);assert.ok(!("last-release-sha" in config));assert.deepEqual(config.packages["."]["extra-files"],[{type:"generic",path:"RELEASE_NOTES.md"}]);assert.match(notes,/x-release-please-version/u);assert.doesNotMatch(workflow,/id-token|attestations|packages: write/u);});
test("the v1.3.5 baseline and notes contract contain only the post-v1.3.4 delta",async()=>{const evidence=await readFile("docs/validation/release-1.3.5-baseline.md","utf8"),changelog=await readFile("CHANGELOG.md","utf8");for(const marker of ["21731941c96525802ee1e31c6df9e888ceab07e7","04a6019e40633fa60cb218548579f02f2e26e880","e9b564c767e89e406047f6c99ad4739d01e61ca5","de964d9bf1294d32a2d0f2e0714736efd2d33310","#100","#104","#103","REST-first field creation","zero GraphQL","user-owned","organization-owned","rollback pin"])assert.ok(evidence.includes(marker),marker);for(const marker of ["04a6019e40633fa60cb218548579f02f2e26e880","e9b564c767e89e406047f6c99ad4739d01e61ca5","de964d9bf1294d32a2d0f2e0714736efd2d33310"])assert.equal(changelog.split(marker).length-1,1,marker);assert.doesNotMatch(changelog,/compare\/yukh-projects-v/u);});
test("release preflight uses the trusted event SHA and emits read-only evidence",async()=>{const workflow=await readFile(".github/workflows/release-preflight.yml","utf8");assert.match(workflow,/permissions:\n  contents: read/u);assert.match(workflow,/RELEASE_COMMIT: \$\{\{ github\.sha \}\}/u);assert.match(workflow,/refs\/heads\/main/u);assert.match(workflow,/release-qualification-\$\{\{ github\.sha \}\}/u);assert.match(workflow,/sha256sum yukh-projects-/u);assert.match(workflow,/release\.spdx\.json/u);assert.match(workflow,/retention-days: 1/u);assert.doesNotMatch(workflow,/ref: \$\{\{ inputs\.|contents: write|id-token: write|attestations: write|gh release|npm publish|git tag|publish-release\.mjs/u);assert.match(workflow,/publication authority/u);});
test("consumer-neutrality policy supports read-only manual recovery",async()=>{const workflow=await readFile(".github/workflows/policy.yml","utf8");assert.match(workflow,/workflow_dispatch:/u);assert.match(workflow,/permissions:\n  contents: read/u);assert.doesNotMatch(workflow,/contents: write|pull-requests: write|id-token: write/u);});
test("merging a Release Please PR publishes without a repository gate",async()=>{const workflow=await readFile(".github/workflows/publish-release.yml","utf8");assert.match(workflow,/push:\n    branches: \[main\]\n    paths: \[\.release-please-manifest\.json\]/u);assert.match(workflow,/permissions:\n  contents: read/u);assert.doesNotMatch(workflow,/workflow_dispatch|environment: release|inputs\./u);assert.equal(workflow.match(/secrets\.RELEASE_TOKEN/gu)?.length,3);assert.match(workflow,/RELEASE_COMMIT: \$\{\{ github\.sha \}\}/u);assert.match(workflow,/contents: write\n      id-token: write\n      attestations: write/u);assert.equal(workflow.match(/git merge-base --is-ancestor "\$RELEASE_COMMIT" origin\/main/gu)?.length,2);assert.equal(workflow.match(/git checkout --detach "\$RELEASE_COMMIT"/gu)?.length,1);assert.equal(workflow.match(/test "\$\(git rev-parse HEAD\)" = "\$RELEASE_COMMIT"/gu)?.length,1);assert.match(workflow,/test "\$\(git rev-parse HEAD\)" = "\$GITHUB_SHA"/u);assert.match(workflow,/node scripts\/check-immutable-releases\.mjs/u);assert.match(workflow,/attest-build-provenance@[0-9a-f]{40}/u);for(const artifact of ["apply-action.yml","dist/apply/action.js","dist/apply/cli.js","dist/apply/index.js","dist/apply/manifest.json"])assert.ok(workflow.includes(artifact));const preflight=workflow.slice(0,workflow.indexOf("  publish:"));assert.doesNotMatch(preflight,/contents: write|id-token: write|attestations: write|publish-release\.mjs/u);});
test("release scripts fail closed and publish only a complete immutable draft",async()=>{const preflight=await readFile("scripts/release-preflight.mjs","utf8"),publisher=await readFile("scripts/publish-release.mjs","utf8"),policy=await readFile("scripts/check-immutable-releases.mjs","utf8");for(const artifact of ["apply-action.yml","dist/apply/action.js","dist/apply/cli.js","dist/apply/index.js","dist/apply/manifest.json"])assert.ok(preflight.includes(artifact)&&publisher.includes(artifact));assert.match(publisher,/body:releaseNotes/u);assert.match(publisher,/IMMUTABLE_RELEASES_READ_TOKEN/u);assert.match(publisher,/headers:policyHeaders/u);assert.match(publisher,/draft:true/u);assert.match(publisher,/JSON\.stringify\(\{draft:false\}\)/u);assert.match(publisher,/immutable!==true/u);assert.doesNotMatch(publisher,/git\/refs.*method:"POST"/u);assert.doesNotMatch(publisher,/generate_release_notes:true|setTimeout|retry|sleep/u);assert.match(policy,/2026-03-10/u);assert.match(policy,/redirect:"error"/u);assert.doesNotMatch(policy,/setTimeout|retry|sleep/u);});
