import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createWouldPublishManifest } from "../src/release-plan.js";

const artifacts=["RELEASE_NOTES.md","action.yml","apply-action.yml","dist/action/index.js","dist/apply/action.js","dist/apply/cli.js","dist/apply/index.js","dist/apply/manifest.json","dist/cli/index.js","dist/mcp-effect-b/index.js","dist/mcp-effect-b/manifest.json","test/fixtures/mcp-effect-b-bridge-v2-vector.json","package-lock.json","release-package.tgz","release-provenance.json","release.spdx.json"].map((path,index)=>({path,bytes:Buffer.from(path==="RELEASE_NOTES.md"?"# Yukh Projects 0.1.0\n\n## Compatibility\n\nSynthetic.\n\n## Rollback\n\nSynthetic.\n":`synthetic-${index}`)}));
test("creates a deterministic non-publishing release manifest",()=>{const a=createWouldPublishManifest("0.1.0","a".repeat(40),"0.1.0","# Changelog\n\n## 0.1.0\n",artifacts);const b=createWouldPublishManifest("0.1.0","a".repeat(40),"0.1.0","## 0.1.0",[...artifacts].reverse());assert.deepEqual(a,b);assert.equal(a.publication,"disabled");assert.equal(a.tag,"v0.1.0");});
test("the checked-in release notes satisfy the exact publication contract",async()=>{const packageDocument=JSON.parse(await readFile("package.json","utf8")) as {version:string},changelog=await readFile("CHANGELOG.md","utf8"),notes=await readFile("RELEASE_NOTES.md");const actualArtifacts=artifacts.map(item=>item.path==="RELEASE_NOTES.md"?{...item,bytes:notes}:item);const candidate=createWouldPublishManifest(packageDocument.version,"a".repeat(40),packageDocument.version,changelog,actualArtifacts);assert.equal(candidate.version,packageDocument.version);});
test("rejects version, commit, changelog, notes, and artifact mismatches",()=>{const badNotes=artifacts.map(item=>item.path==="RELEASE_NOTES.md"?{...item,bytes:Buffer.from("# Yukh Projects 0.2.0\n\n## Compatibility\n\nSynthetic.\n\n## Rollback\n\nSynthetic.\n")}:item);const cases:readonly [string,string,string,string,typeof artifacts][]=[["v0.1.0","a".repeat(40),"0.1.0","## 0.1.0",artifacts],["0.1.0","short","0.1.0","## 0.1.0",artifacts],["0.1.0","a".repeat(40),"0.2.0","## 0.1.0",artifacts],["0.1.0","a".repeat(40),"0.1.0","# Changelog",artifacts],["0.1.0","a".repeat(40),"0.1.0","## 0.1.0",badNotes],["0.1.0","a".repeat(40),"0.1.0","## 0.1.0",artifacts.slice(1)],["0.1.0","a".repeat(40),"0.1.0","## 0.1.0",[...artifacts.slice(0,-1),{path:"unexpected",bytes:Buffer.from("value")}]]];for(const [version,commit,packageVersion,changelog,files] of cases)assert.throws(()=>createWouldPublishManifest(version,commit,packageVersion,changelog,files));});
