import assert from "node:assert/strict";
import test from "node:test";
import { createGovernedHandoffReceipt } from "../src/deferred-receipt.js";
import { createResumableDeferralHost, type DeferredHostState } from "../src/resumable-deferral-host.js";

const now=1_800_000_000_000,digest=(c:string)=>c.repeat(64),handoff=()=>createGovernedHandoffReceipt({resource:"graphql",issuedAtMs:now,resumeAfterMs:now+100,resumeByMs:now+1000,scopeDigest:digest("a"),requestDigest:digest("b"),planDigest:digest("c"),freshApprovalRequired:true});
function fixture(clock=now+100){let state:DeferredHostState="deferred",cancelled=0;const host=createResumableDeferralHost({schedule:async()=>({wakeupDigest:digest("d"),cancellationDigest:digest("e")}),state:async()=>state,cancel:async()=>{cancelled++;state="cancelled";}},()=>clock);return{host,setState:(value:DeferredHostState)=>{state=value;},cancelled:()=>cancelled};}

test("retains ownership only after durable scheduling returns redacted handles",async()=>{const{host}=fixture(now);const receipt=await host.retain(handoff());assert.equal(receipt.ownership.disposition,"retained");assert.equal(receipt.ownership.wakeup_digest,digest("d"));});
test("resume starts a fresh process with bindings and approval requirement",async()=>{const{host,setState}=fixture();const receipt=await host.retain(handoff());setState("resumable");let calls=0;const result=await host.resume(receipt,async(bindings,fresh)=>{calls++;assert.equal(bindings.request_digest,digest("b"));assert.equal(fresh,true);return{status:"complete"};});assert.equal(result.status,"complete");assert.equal(calls,1);});
test("unavailable, cancelled, early, and expired wakeups never run",async()=>{const first=fixture(),receipt=await first.host.retain(handoff());let calls=0;assert.equal((await first.host.resume(receipt,async()=>{calls++;return{status:"complete"};})).status,"blocked");await first.host.cancel(receipt);assert.equal(first.cancelled(),1);assert.equal(calls,0);await assert.rejects(()=>fixture(now+99).host.resume(receipt,async()=>({status:"complete"})),/invalid deferral transition/u);await assert.rejects(()=>fixture(now+1001).host.resume(receipt,async()=>({status:"complete"})),/invalid deferral transition/u);});
test("a fresh process may defer again without replaying the prior request",async()=>{const{host,setState}=fixture(),receipt=await host.retain(handoff());setState("resumable");const next=createGovernedHandoffReceipt({resource:"rest",issuedAtMs:now+100,scopeDigest:digest("a"),requestDigest:digest("f"),planDigest:null,freshApprovalRequired:true}),result=await host.resume(receipt,async()=>({status:"deferred",receipt:next}));assert.equal(result.status,"deferred");assert.equal(result.receipt?.reason,"rest-reserve");assert.notEqual(result.receipt?.bindings.request_digest,receipt.bindings.request_digest);});
