import { readFile } from "node:fs/promises";
import { createHash } from "node:crypto";

const [version,commit,assetDirectory="release-assets"]=process.argv.slice(2),repository=process.env.GITHUB_REPOSITORY,token=process.env.GITHUB_TOKEN;
if(!/^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)$/u.test(version??"")||!/^[0-9a-f]{40}$/u.test(commit??"")||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/u.test(repository??"")||!token)throw new Error("publication binding is invalid");
const tag=`v${version}`,base=`https://api.github.com/repos/${repository}`,headers={accept:"application/vnd.github+json",authorization:`Bearer ${token}`,"x-github-api-version":"2022-11-28"};
async function request(url,init={}){const response=await fetch(url,{...init,headers:{...headers,...init.headers},redirect:"error"});if(response.status===404)return undefined;if(!response.ok)throw new Error(`GitHub publication request failed (${response.status})`);const value=await response.json();if(!value||typeof value!=="object")throw new Error("GitHub publication receipt is invalid");return value;}
const manifest=JSON.parse(await readFile(`${assetDirectory}/would-publish.json`,"utf8"));if(manifest.version!==version||manifest.commit!==commit||manifest.tag!==tag||manifest.publication!=="disabled")throw new Error("publication manifest mismatch");
const mapping=new Map([["RELEASE_NOTES.md",`yukh-projects-release-notes-${version}.md`],["action.yml",`yukh-projects-action-${version}.yml`],["apply-action.yml",`yukh-projects-apply-action-${version}.yml`],["dist/action/index.js",`yukh-projects-action-${version}.js`],["dist/apply/action.js",`yukh-projects-apply-action-${version}.js`],["dist/apply/cli.js",`yukh-projects-apply-cli-${version}.js`],["dist/apply/index.js",`yukh-projects-apply-library-${version}.js`],["dist/apply/manifest.json",`yukh-projects-apply-manifest-${version}.json`],["dist/cli/index.js",`yukh-projects-cli-${version}.js`],["package-lock.json",`yukh-projects-lock-${version}.json`],["release.spdx.json",`yukh-projects-${version}.spdx.json`]]),digests=new Map(),assets=[];
for(const item of manifest.artifacts){const name=mapping.get(item.path);if(!name)throw new Error("publication artifact is not allowlisted");const bytes=await readFile(`${assetDirectory}/${name}`),digest=createHash("sha256").update(bytes).digest("hex");if(bytes.byteLength!==item.bytes||digest!==item.sha256)throw new Error("publication artifact digest mismatch");digests.set(name,digest);assets.push(name);}assets.sort();const checksum=`yukh-projects-${version}.sha256`,checksumBytes=await readFile(`${assetDirectory}/${checksum}`,"utf8"),expectedChecksums=assets.map(name=>`${digests.get(name)}  ${name}\n`).join("");if(checksumBytes!==expectedChecksums)throw new Error("publication checksum manifest mismatch");assets.push(checksum);
if(await request(`${base}/git/ref/tags/${encodeURIComponent(tag)}`)!==undefined||await request(`${base}/releases/tags/${encodeURIComponent(tag)}`)!==undefined)throw new Error("publication state already exists");
const tagReceipt=await request(`${base}/git/refs`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ref:`refs/tags/${tag}`,sha:commit})});if(tagReceipt?.object?.sha!==commit)throw new Error("published tag receipt mismatch");
const releaseNotes=await readFile(`${assetDirectory}/yukh-projects-release-notes-${version}.md`,"utf8");if(releaseNotes.length<1||releaseNotes.length>64*1024)throw new Error("release notes are invalid");const release=await request(`${base}/releases`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tag_name:tag,target_commitish:commit,name:`Yukh Projects ${tag}`,body:releaseNotes,draft:false,prerelease:false,generate_release_notes:false})});if(typeof release?.id!=="number"||typeof release?.upload_url!=="string")throw new Error("published release receipt mismatch");
for(const name of assets){const bytes=await readFile(`${assetDirectory}/${name}`),url=release.upload_url.replace("{?name,label}",`?name=${encodeURIComponent(name)}`);const receipt=await request(url,{method:"POST",headers:{"content-type":"application/octet-stream","content-length":String(bytes.byteLength)},body:bytes});if(receipt?.name!==name)throw new Error("published asset receipt mismatch");}
const verified=await request(`${base}/releases/tags/${encodeURIComponent(tag)}`);if(verified?.id!==release.id||verified?.tag_name!==tag)throw new Error("published release verification mismatch");
