import { constants, createReadStream } from "node:fs";
import { open, realpath } from "node:fs/promises";
import { basename, dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { parseRuntimeScope } from "./runtime-input.js";
import { parseControlledApplyMode, type ControlledApplyMode } from "./apply-mode.js";

export interface ApplyCliOptions{mode:ControlledApplyMode;owner:string;repository:string;projectNumber:string;issueNumber:string;policyPath:string;approvedPlanId:string;approvalFile:string;approvalPublicKeyFile:string;environment:string;readTokenFd:number;writeTokenFd:number;hostCapsuleFd:number}
const VALUES=new Set(["--mode","--owner","--repository","--project-number","--issue-number","--policy-path","--approved-plan-id","--approval-file","--approval-public-key-file","--environment","--github-read-token-fd","--github-write-token-fd","--host-capsule-fd"]),DIGEST=/^[a-f0-9]{64}$/u,FD=/^(?:[3-9][0-9]{0,2}|1[0-9]{3})$/u;
function bounded(value:string,max=256):boolean{return value.length>0&&value.length<=max&&!/[\u0000-\u001f\u007f]/u.test(value);}
function fd(value:string|undefined):number{if(!value||!FD.test(value))throw new TypeError("invalid apply arguments");const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed>1024)throw new TypeError("invalid apply arguments");return parsed;}
export function parseApplyCliArgs(argv:readonly string[]):ApplyCliOptions{const values=new Map<string,string>();for(let index=0;index<argv.length;index++){const key=argv[index]!;if(!VALUES.has(key)||values.has(key))throw new TypeError("invalid apply arguments");const value=argv[++index];if(value===undefined||value.startsWith("--")||!bounded(value,1024))throw new TypeError("invalid apply arguments");values.set(key,value);}for(const key of VALUES)if(key!=="--policy-path"&&!values.has(key))throw new TypeError("invalid apply arguments");let mode:ControlledApplyMode;try{mode=parseControlledApplyMode(values.get("--mode")??"");}catch{throw new TypeError("invalid apply arguments");}if(!DIGEST.test(values.get("--approved-plan-id")??"")||!bounded(values.get("--environment")??"",64))throw new TypeError("invalid apply arguments");parseRuntimeScope({owner:values.get("--owner")!,repository:values.get("--repository")!,projectNumber:values.get("--project-number")!,issueNumber:values.get("--issue-number")!});const readTokenFd=fd(values.get("--github-read-token-fd")),writeTokenFd=fd(values.get("--github-write-token-fd")),hostCapsuleFd=fd(values.get("--host-capsule-fd"));if(new Set([readTokenFd,writeTokenFd,hostCapsuleFd]).size!==3)throw new TypeError("invalid apply arguments");return{mode,owner:values.get("--owner")!,repository:values.get("--repository")!,projectNumber:values.get("--project-number")!,issueNumber:values.get("--issue-number")!,policyPath:values.get("--policy-path")??".yukh/project.yaml",approvedPlanId:values.get("--approved-plan-id")!,approvalFile:values.get("--approval-file")!,approvalPublicKeyFile:values.get("--approval-public-key-file")!,environment:values.get("--environment")!,readTokenFd,writeTokenFd,hostCapsuleFd};}

export async function readRunnerCapsule(runnerTemp:string,name:string):Promise<string>{if(!bounded(name,128)||name.includes("/")||name.includes("\\")||name==="."||name==="..")throw new TypeError("invalid host capsule file");const root=await realpath(runnerTemp),path=resolve(root,name),handle=await open(path,constants.O_RDONLY|constants.O_NOFOLLOW);try{const metadata=await handle.stat();if(!metadata.isFile()||metadata.size<1||metadata.size>64*1024||(metadata.mode&0o777)!==0o600)throw new TypeError("invalid host capsule file");return(await handle.readFile()).toString("utf8");}finally{await handle.close();}}

export async function readBoundedFd(fdValue:number,maxBytes=8192):Promise<string>{if(!Number.isSafeInteger(fdValue)||fdValue<3||fdValue>1024||maxBytes<1||maxBytes>64*1024)throw new TypeError("invalid credential descriptor");let bytes=0,value="";for await(const chunk of createReadStream("",{fd:fdValue,autoClose:true})){const buffer=Buffer.from(chunk);bytes+=buffer.byteLength;if(bytes>maxBytes)throw new TypeError("invalid credential");value+=buffer.toString("utf8");}value=value.replace(/\r?\n$/u,"");if(!value||/[\u0000-\u001f\u007f]/u.test(value))throw new TypeError("invalid credential");return value;}

export async function readExclusiveWorkspaceFile(workspace:string,filePath:string,maxBytes=64*1024):Promise<Buffer>{if(!bounded(filePath,1024)||isAbsolute(filePath)||filePath.split(/[\\/]/u).includes("..")||maxBytes<1||maxBytes>1024*1024)throw new TypeError("invalid protected file");const root=await realpath(workspace),candidate=resolve(root,filePath),parent=await realpath(dirname(candidate)),rel=relative(root,parent);if(rel===".."||rel.startsWith(`..${sep}`)||isAbsolute(rel))throw new TypeError("invalid protected file");const resolved=resolve(parent,basename(candidate)),handle=await open(resolved,constants.O_RDONLY|constants.O_NOFOLLOW);try{const metadata=await handle.stat();if(!metadata.isFile()||metadata.size<1||metadata.size>maxBytes)throw new TypeError("invalid protected file");const value=await handle.readFile();if(value.length<1||value.length>maxBytes)throw new TypeError("invalid protected file");return value;}finally{await handle.close();}}

export async function readApprovalArtifact(workspace:string,filePath:string):Promise<unknown>{const bytes=await readExclusiveWorkspaceFile(workspace,filePath);try{return JSON.parse(bytes.toString("utf8"));}catch{throw new TypeError("invalid approval artifact");}}
