import { loadWorkspacePolicy, parseRuntimeScope } from "./runtime-input.js";
import { readApprovalArtifact, readExclusiveWorkspaceFile } from "./apply-runtime-input.js";
import { runApplyEntrypoint } from "./apply-entrypoint.js";
import { allowsSharedControlledApplyCredential, parseControlledApplyMode, reconciliationModeForControlledApply, type ControlledApplyMode } from "./apply-mode.js";
import type { ApplyHostFactory } from "./apply-host.js";
import type { PublicApplyReport } from "./executor.js";

export type ApplyActionMode=ControlledApplyMode;
export interface ApplyActionIO{env:Readonly<Record<string,string|undefined>>;mask(value:string):void;output(name:string,value:string):Promise<void>;error(code:string):void}
function input(io:ApplyActionIO,name:string):string{const value=io.env[`INPUT_${name.toUpperCase()}`];if(value===undefined||value==="")throw new TypeError("invalid action input");return value;}
export function parseApplyActionMode(value:string):ApplyActionMode{return parseControlledApplyMode(value);}
export function allowsSharedApplyCredential(mode:ApplyActionMode):boolean{return allowsSharedControlledApplyCredential(mode);}
function failure(planId:string):PublicApplyReport{return{schema:1,status:"error",planId:/^[a-f0-9]{64}$/u.test(planId)?planId:"invalid",counts:{already_converged:0,verified:0,failed:0,not_attempted:0},remaining:0,diagnostics:[{code:"YKP-APPLY-001",severity:"error",message:"apply request is invalid"}]};}
export async function applyActionMain(io:ApplyActionIO,factory:ApplyHostFactory):Promise<PublicApplyReport>{let approvedPlanId="invalid";try{const mode=parseApplyActionMode(input(io,"MODE"));const readToken=input(io,"GITHUB-READ-TOKEN");io.mask(readToken);const writeToken=input(io,"GITHUB-WRITE-TOKEN");io.mask(writeToken);if(readToken===writeToken&&!allowsSharedApplyCredential(mode))throw new TypeError("credential profiles must be distinct");approvedPlanId=input(io,"APPROVED-PLAN-ID");const workspace=io.env.GITHUB_WORKSPACE;if(!workspace)throw new TypeError("invalid action environment");const requestedScope=parseRuntimeScope({owner:input(io,"OWNER"),repository:input(io,"REPOSITORY"),projectNumber:input(io,"PROJECT-NUMBER"),issueNumber:input(io,"ISSUE-NUMBER")}),[policySource,approvalArtifact,approvalPublicKey]=await Promise.all([loadWorkspacePolicy(workspace,io.env["INPUT_POLICY-PATH"]||".yukh/project.yaml"),readApprovalArtifact(workspace,input(io,"APPROVAL-FILE")),readExclusiveWorkspaceFile(workspace,input(io,"APPROVAL-PUBLIC-KEY-FILE"))]),runtime=await factory.create({reconciliationMode:reconciliationModeForControlledApply(mode),requestedScope,policySource,readToken,writeToken}),report=await runApplyEntrypoint({approvedPlanId,protectedEnvironment:input(io,"ENVIRONMENT"),scope:runtime.scope,approvalArtifact,approvalPublicKey},runtime.host),receipt=report.status==="deferred"?runtime.deferredReceipt?.():undefined;await io.output("status",report.status);await io.output("plan-id",report.planId);await io.output("remaining",String(report.remaining));await io.output("report",JSON.stringify(report));await io.output("deferred-receipt",receipt?JSON.stringify(receipt):"");if(report.status!=="success")io.error(report.diagnostics[0]?.code??"YKP-APPLY-001");return report;}catch{const report=failure(approvedPlanId);io.error("YKP-APPLY-001");return report;}}
