import { ApplyCoordinationError, type ApplyCoordinationStore, type ApplyLease, type LeaseRequest, type NonceRequest } from "./apply-coordination.js";

const MEDIA="application/yukh-coordination-primitives+json;version=1",DIGEST=/^[a-f0-9]{64}$/u,MAX_BODY=4096,MAX_CAPABILITY=3800;
export interface CoordinationAuthenticationRequest{method:"POST";targetUri:string;signal:AbortSignal}
export interface CoordinationAuthentication{credential:string;proof:string}
export interface ApplyCoordinationHttpOptions{baseUri:string;epoch:number;deadlineMs:number;authenticate(request:CoordinationAuthenticationRequest):Promise<CoordinationAuthentication>;fetch?:typeof globalThis.fetch}

function canonical(value:unknown):string{if(value===null||typeof value==="boolean"||typeof value==="string")return JSON.stringify(value);if(typeof value==="number"){if(!Number.isSafeInteger(value))throw new ApplyCoordinationError("YKP-COORD-001");return JSON.stringify(value);}if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(typeof value!=="object")throw new ApplyCoordinationError("YKP-COORD-001");const record=value as Record<string,unknown>,keys=Object.keys(record).sort();return`{${keys.map(key=>`${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`;}
function expiry(value:number):string{if(!Number.isSafeInteger(value))throw new ApplyCoordinationError("YKP-COORD-001");const formatted=new Date(value).toISOString();if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(formatted))throw new ApplyCoordinationError("YKP-COORD-001");return formatted;}
function validRequest(value:NonceRequest|LeaseRequest,epoch:number):boolean{return DIGEST.test(value.keyDigest)&&DIGEST.test("valueDigest"in value?value.valueDigest:value.holderDigest)&&value.epoch===epoch&&Number.isSafeInteger(value.expiresAtMs);}
function object(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value);}

function beforeDeadline<T>(promise:Promise<T>,signal:AbortSignal):Promise<T>{if(signal.aborted)return Promise.reject(new ApplyCoordinationError("YKP-COORD-002"));return new Promise<T>((resolve,reject)=>{const aborted=()=>reject(new ApplyCoordinationError("YKP-COORD-002"));signal.addEventListener("abort",aborted,{once:true});promise.then(value=>{signal.removeEventListener("abort",aborted);resolve(value);},error=>{signal.removeEventListener("abort",aborted);reject(error);});});}
async function bounded(response:Response,signal:AbortSignal):Promise<unknown>{const reader=response.body?.getReader();if(!reader)throw new ApplyCoordinationError("YKP-COORD-001");const chunks:Uint8Array[]=[];let length=0;try{for(;;){const{done,value}=await beforeDeadline(reader.read(),signal);if(done)break;if(!(value instanceof Uint8Array)||(length+=value.byteLength)>MAX_BODY){await reader.cancel();throw new ApplyCoordinationError("YKP-COORD-001");}chunks.push(value);}}catch(error){if(error instanceof ApplyCoordinationError)throw error;throw new ApplyCoordinationError("YKP-COORD-002");}finally{reader.releaseLock();}const bytes=new Uint8Array(length);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}let text:string;try{text=new TextDecoder("utf-8",{fatal:true}).decode(bytes);}catch{throw new ApplyCoordinationError("YKP-COORD-001");}let parsed:unknown;try{parsed=JSON.parse(text);}catch{throw new ApplyCoordinationError("YKP-COORD-001");}if(canonical(parsed)!==text)throw new ApplyCoordinationError("YKP-COORD-001");return parsed;}

export function createApplyCoordinationHttpStore(options:ApplyCoordinationHttpOptions):ApplyCoordinationStore{
 let base:URL;try{base=new URL(options?.baseUri);}catch{throw new TypeError("invalid coordination configuration");}if(base.protocol!=="https:"||base.username||base.password||base.search||base.hash||base.pathname!=="/"||options.baseUri.endsWith("/")||!Number.isSafeInteger(options.epoch)||options.epoch<1||!Number.isSafeInteger(options.deadlineMs)||options.deadlineMs<1||options.deadlineMs>5000||typeof options.authenticate!=="function")throw new TypeError("invalid coordination configuration");const fetcher=options.fetch??globalThis.fetch;
 async function call(path:string,body:Record<string,unknown>):Promise<Record<string,unknown>>{const target=`${options.baseUri}${path}`,raw=canonical(body);if(Buffer.byteLength(raw)>MAX_BODY)throw new ApplyCoordinationError("YKP-COORD-001");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.deadlineMs);try{let auth:CoordinationAuthentication;try{auth=await beforeDeadline(options.authenticate({method:"POST",targetUri:target,signal:controller.signal}),controller.signal);}catch{throw new ApplyCoordinationError("YKP-COORD-002");}if(typeof auth?.credential!=="string"||auth.credential.length<1||auth.credential.length>8192||typeof auth.proof!=="string"||auth.proof.length<1||auth.proof.length>16384)throw new ApplyCoordinationError("YKP-COORD-001");let response:Response;try{response=await fetcher(target,{method:"POST",redirect:"manual",signal:controller.signal,headers:{authorization:`DPoP ${auth.credential}`,dpop:auth.proof,"content-type":MEDIA},body:raw});}catch{throw new ApplyCoordinationError("YKP-COORD-002");}if(response.status>=300&&response.status<400)throw new ApplyCoordinationError("YKP-COORD-002");if(response.headers.get("content-type")?.split(";").map(part=>part.trim()).join(";")!==MEDIA)throw new ApplyCoordinationError("YKP-COORD-001");const parsed=await bounded(response,controller.signal);if(!object(parsed))throw new ApplyCoordinationError("YKP-COORD-001");if(!response.ok){if(response.status===401)throw new ApplyCoordinationError("YKP-COORD-004");if(response.status===403)throw new ApplyCoordinationError("YKP-COORD-005");const code=parsed.code;throw new ApplyCoordinationError(code==="conflict"||code==="replayed"||code==="stale_fence"?"YKP-COORD-003":code==="temporarily_unavailable"?"YKP-COORD-002":"YKP-COORD-001");}if(parsed.specversion!=="1"||typeof parsed.outcome!=="string")throw new ApplyCoordinationError("YKP-COORD-001");return parsed;}finally{clearTimeout(timer);}}
 return{
  consumeNonce:async request=>{if(!validRequest(request,options.epoch))throw new ApplyCoordinationError("YKP-COORD-001");const result=await call("/coordination-primitives/v1/nonces:consume",{epoch:request.epoch,expires_at:expiry(request.expiresAtMs),scope_digest:request.keyDigest,value_digest:request.valueDigest});if(result.outcome!=="consumed"&&result.outcome!=="replayed")throw new ApplyCoordinationError("YKP-COORD-001");return result.outcome;},
  acquireLease:async request=>{if(!validRequest(request,options.epoch))throw new ApplyCoordinationError("YKP-COORD-001");let result:Record<string,unknown>;try{result=await call("/coordination-primitives/v1/leases:acquire",{epoch:request.epoch,expires_at:expiry(request.expiresAtMs),holder_digest:request.holderDigest,scope_digest:request.keyDigest});}catch(error){if(error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-003")return null;throw error;}if(result.outcome!=="acquired"||typeof result.lease_capability!=="string"||result.lease_capability.length<1||result.lease_capability.length>MAX_CAPABILITY||!Number.isSafeInteger(result.fencing_token)||Number(result.fencing_token)<1)throw new ApplyCoordinationError("YKP-COORD-001");let capability=result.lease_capability,fencingToken=Number(result.fencing_token);const lease:ApplyLease={get fencingToken(){return fencingToken;},renew:async expiresAtMs=>{try{const renewed=await call("/coordination-primitives/v1/leases:renew",{expires_at:expiry(expiresAtMs),lease_capability:capability});if(renewed.outcome!=="renewed"||typeof renewed.lease_capability!=="string"||renewed.lease_capability.length<1||renewed.lease_capability.length>MAX_CAPABILITY||!Number.isSafeInteger(renewed.fencing_token)||Number(renewed.fencing_token)<=fencingToken)throw new ApplyCoordinationError("YKP-COORD-001");capability=renewed.lease_capability;fencingToken=Number(renewed.fencing_token);return true;}catch(error){if(error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-003")return false;throw error;}},valid:async()=>{const inspected=await call("/coordination-primitives/v1/leases:inspect",{lease_capability:capability});if(!["valid","expired","released","stale"].includes(String(inspected.outcome)))throw new ApplyCoordinationError("YKP-COORD-001");return inspected.outcome==="valid";},release:async()=>{try{const released=await call("/coordination-primitives/v1/leases:release",{lease_capability:capability});return released.outcome==="released";}catch(error){if(error instanceof ApplyCoordinationError&&error.code==="YKP-COORD-003")return false;throw error;}}};return lease;}
 };
}
