import { createApplyCoordinationHttpStore } from "./apply-coordination-http.js";
import type { ApplyHostFactory } from "./apply-host.js";
import { ApplyPortError, type MutationKind } from "./executor.js";
import { normalizeGitHubApplyFailure } from "./github-apply-failure.js";
import { createGitHubMutationTransport, type MutationVariables } from "./github-mutation-transport.js";
import { createGitHubRateLedger } from "./github-rate-ledger.js";
import { createRestProjectSnapshotReader, snapshotInvalidationForMutation, type SnapshotInput } from "./github-rest-snapshot.js";
import { planLegacyReconciliation } from "./legacy-plan.js";
import { parseLegacyPolicy } from "./legacy-shadow.js";
import { canonicalJson, type PlannedOperation } from "./planner.js";
import type { ControlledApplyHostOptions } from "./controlled-apply-host.js";

const KIND:Record<PlannedOperation["type"],MutationKind>={create_field:"create_project_field",add_option:"update_project_field_options",set_field_value:"update_project_item_field_value",set_issue_type:"set_issue_type",set_parent:"add_sub_issue",add_dependency:"add_blocked_by"};
function sameResource(a:PlannedOperation,b:PlannedOperation):boolean{return a.resource.kind===b.resource.kind&&a.resource.logicalKey===b.resource.logicalKey&&a.resource.scopeRef===b.resource.scopeRef;}
function exact(a:PlannedOperation,b:PlannedOperation):boolean{return canonicalJson(a)===canonicalJson(b);}

export function createControlledLegacyApplyHostFactory(options:ControlledApplyHostOptions):ApplyHostFactory{
 if(!options||options.coordination.epoch!==options.coordinationEpoch||options.allowedIssuerRefs.length<1||new Set(options.allowedIssuerRefs).size!==options.allowedIssuerRefs.length)throw new TypeError("invalid controlled apply host configuration");const coordinationStore=createApplyCoordinationHttpStore(options.coordination),clock=options.nowMs??Date.now;
 return{create:async input=>{if(input.readToken===input.writeToken)throw new TypeError("credential profiles must be distinct");const policy=parseLegacyPolicy(input.policySource),includeIssueTypes=Object.values(policy.fields).some(field=>field.target==="issue_type"),ledger=createGitHubRateLedger(options.rate),reader=createRestProjectSnapshotReader({token:input.readToken,fetch:options.readFetch,rateLedger:ledger,graphqlRemaining:options.rate.graphqlRemaining,includeIssueTypes}),snapshotInput:SnapshotInput={ownerLogin:input.requestedScope.ownerLogin,repositoryName:input.requestedScope.repositoryName,projectNumber:input.requestedScope.projectNumber,issueNumbers:[input.requestedScope.issueNumber]},mutation=createGitHubMutationTransport({token:input.writeToken,permissions:options.permissions,approvedKinds:options.approvedKinds,fetch:options.writeFetch,rateLedger:ledger});
  const replan=async()=>planLegacyReconciliation(input.policySource,await reader.read(snapshotInput),input.requestedScope.issueNumber),initial=await reader.read(snapshotInput),scope={subjectRef:initial.subjectRef,repositoryRef:initial.repositoryRef,projectRef:initial.projectRef,issueRef:initial.issues.get(input.requestedScope.issueNumber)!.issueRef,issueNumber:input.requestedScope.issueNumber};
  const variables=async(operation:PlannedOperation):Promise<MutationVariables>=>{const snapshot=await reader.read(snapshotInput),issue=snapshot.issues.get(input.requestedScope.issueNumber);if(!issue)throw new ApplyPortError("invariant");const declaration=policy.fields[operation.resource.logicalKey];
   if(operation.type==="create_field"){const repositoryOwner=snapshot.repositoryOwnerKind??snapshot.ownerKind;if(!declaration||declaration.target!=="project_field"&&!(declaration.target==="issue_type"&&repositoryOwner==="users"))throw new ApplyPortError("invariant");const names=Object.values(declaration.values);return{kind:"create_project_field",ownerKind:snapshot.projectOwnerKind??snapshot.ownerKind,ownerLogin:snapshot.projectOwnerLogin??snapshot.ownerLogin,projectNumber:snapshot.projectNumber,dataType:names.length?"SINGLE_SELECT":declaration.type==="number"?"NUMBER":declaration.type==="date"?"DATE":"TEXT",name:declaration.projectField,...(names.length?{options:[...new Set(names)].sort().map(name=>({name,color:"GRAY" as const,description:""}))}:{})};}
   if(operation.type==="set_field_value"){if(!declaration)throw new ApplyPortError("invariant");const field=snapshot.fields.find(value=>value.name===declaration.projectField);if(!field)throw new ApplyPortError("invariant");const desired=operation.desired;const value=field.kind==="number"?{number:Number(desired)}:field.kind==="date"?{date:String(desired)}:field.kind==="text"?{text:String(desired)}:(()=>{const option=field.options.find(value=>value.name===String(desired));if(!option)throw new ApplyPortError("invariant");return{singleSelectOptionId:option.id};})();return{kind:"update_project_item_field_value",projectId:snapshot.projectRef,itemId:issue.itemRef,fieldId:field.id,value};}
   if(operation.type==="set_issue_type"){if(typeof operation.desired!=="string")throw new ApplyPortError("invariant");return{kind:"set_issue_type",ownerLogin:snapshot.ownerLogin,repositoryName:snapshot.repositoryName,issueNumber:input.requestedScope.issueNumber,issueTypeName:operation.desired};}
   if(operation.type==="set_parent"){const parent=Number(operation.desired),related=await reader.read({...snapshotInput,issueNumbers:[input.requestedScope.issueNumber,parent]}),parentIssue=related.issues.get(parent);if(!parentIssue)throw new ApplyPortError("invariant");return{kind:"add_sub_issue",parentIssueId:parentIssue.issueRef,subIssueId:issue.issueRef};}
   throw new ApplyPortError("invariant");};
  return{scope,host:{enablement:options.enablement,allowedIssuerRefs:options.allowedIssuerRefs,holderDigest:options.holderDigest,coordinationEpoch:options.coordinationEpoch,coordinationStore,ports:{nowMs:clock,replan,admit:async kinds=>{try{return mutation.admit(kinds);}catch(error){throw normalizeGitHubApplyFailure(error);}},inspect:async operation=>{const plan=await replan(),found=plan.operations.find(candidate=>candidate.operationKey===operation.operationKey);if(found)return exact(found,operation)?"ready":"mismatch";return plan.operations.some(candidate=>sameResource(candidate,operation))?"mismatch":"already_converged";},mutate:async(kind,operation,clientMutationId)=>{if(KIND[operation.type]!==kind)throw new ApplyPortError("invariant");try{await mutation.execute(kind,await variables(operation),clientMutationId);}catch(error){throw normalizeGitHubApplyFailure(error);}},invalidateAfterMutation:async kind=>reader.invalidate(snapshotInput,snapshotInvalidationForMutation(kind)),verify:async operation=>{const plan=await replan();return!plan.operations.some(candidate=>sameResource(candidate,operation));},audit:options.audit??(async()=>{})}}};}};
}
