import { createApplyCoordinationHttpStore, type ApplyCoordinationHttpOptions } from "./apply-coordination-http.js";
import { prepareReconciliation, type PreparedReconciliation } from "./dry-run.js";
import { ApplyPortError, type MutationKind } from "./executor.js";
import { normalizeGitHubApplyFailure } from "./github-apply-failure.js";
import { createGitHubMutationTransport, type MutationVariables, type PermissionAttestation } from "./github-mutation-transport.js";
import { createGitHubRateLedger, type GitHubRateLedgerOptions } from "./github-rate-ledger.js";
import { createGitHubRestSnapshotReadTransportFromReader, createRestProjectSnapshotReader, snapshotInvalidationForMutation, type RestProjectSnapshot, type RestProjectSnapshotReader, type SnapshotInput } from "./github-rest-snapshot.js";
import type { ApplyHostFactory, ApplyHostFactoryInput } from "./apply-host.js";
import { canonicalJson, type PlannedOperation } from "./planner.js";
import { createHash } from "node:crypto";
import { createGovernedHandoffReceipt } from "./deferred-receipt.js";
import { createControlledLegacyApplyHostFactory } from "./controlled-legacy-apply-host.js";

export interface ControlledApplyHostOptions{
 enablement:"disabled"|"apply-explicitly-enabled";allowedIssuerRefs:readonly string[];holderDigest:string;coordinationEpoch:number;
 coordination:ApplyCoordinationHttpOptions;permissions:PermissionAttestation;approvedKinds:readonly MutationKind[];rate:GitHubRateLedgerOptions;
 readFetch?:typeof globalThis.fetch;writeFetch?:typeof globalThis.fetch;nowMs?:()=>number;audit?(event:{type:string;planId:string;operationKey?:string;outcome:string}):Promise<void>;
}
type Success=Extract<PreparedReconciliation,{status:"success"}>;
type FieldValue=Extract<MutationVariables,{kind:"update_project_item_field_value"}>["value"];
const KIND:Record<PlannedOperation["type"],MutationKind>={create_field:"create_project_field",add_option:"update_project_field_options",set_field_value:"update_project_item_field_value",set_issue_type:"set_issue_type",set_parent:"add_sub_issue",add_dependency:"add_blocked_by"};
function failure(value:Exclude<PreparedReconciliation,Success>):never{throw new ApplyPortError(value.failureClass==="authentication"?"authentication":value.failureClass==="authorization"?"authorization":value.failureClass==="deferred"?"deferred_rate_budget":value.failureClass==="provider"?"provider":"invariant");}
function sameResource(a:PlannedOperation,b:PlannedOperation):boolean{return a.resource.kind===b.resource.kind&&a.resource.logicalKey===b.resource.logicalKey&&a.resource.scopeRef===b.resource.scopeRef;}
function exact(a:PlannedOperation,b:PlannedOperation):boolean{return canonicalJson(a)===canonicalJson(b);}
function digest(value:unknown):string{return createHash("sha256").update(canonicalJson(value)).digest("hex");}
function field(snapshot:RestProjectSnapshot,prepared:Success,key:string){const declaration=prepared.policy.fields[key],found=declaration&&snapshot.fields.find(value=>value.name===declaration.name);if(!declaration||!found)throw new ApplyPortError("invariant");return{declaration,found};}
async function variables(operation:PlannedOperation,prepared:Success,reader:RestProjectSnapshotReader,input:SnapshotInput):Promise<MutationVariables>{
 const snapshot=await reader.read(input),issue=snapshot.issues.get(input.issueNumbers[0]!);if(!issue)throw new ApplyPortError("invariant");
 if(operation.type==="create_field"){const declaration=prepared.policy.fields[operation.resource.logicalKey];if(!declaration||declaration.kind==="iteration")throw new ApplyPortError("invariant");const dataType={text:"TEXT",number:"NUMBER",date:"DATE",single_select:"SINGLE_SELECT"} as const;return{kind:"create_project_field",ownerKind:snapshot.projectOwnerKind??snapshot.ownerKind,ownerLogin:snapshot.projectOwnerLogin??snapshot.ownerLogin,projectNumber:snapshot.projectNumber,dataType:dataType[declaration.kind],name:declaration.name,...(declaration.kind==="single_select"?{options:Object.values(declaration.options??{}).map(name=>({name,color:"GRAY" as const,description:""}))}:{})};}
 if(operation.type==="add_option"){const key=operation.resource.logicalKey.split(".")[0]!,{declaration,found}=field(snapshot,prepared,key),name=String(operation.desired??declaration.options?.[operation.resource.logicalKey.split(".")[1]??""]);if(!name||found.options.some(option=>option.color===undefined||option.description===undefined))throw new ApplyPortError("invariant");return{kind:"update_project_field_options",fieldId:found.id,observedOptions:found.options.map(option=>({id:option.id,name:option.name,color:option.color!,description:option.description!})),newOption:{name,color:"GRAY",description:""}};}
 if(operation.type==="set_field_value"){const{declaration,found}=field(snapshot,prepared,operation.resource.logicalKey);let value:FieldValue;if(declaration.kind==="number")value={number:Number(operation.desired)};else if(declaration.kind==="date")value={date:String(operation.desired)};else if(declaration.kind==="text")value={text:String(operation.desired)};else{const option=found.options.find(candidate=>candidate.name===String(operation.desired));if(!option)throw new ApplyPortError("invariant");value=declaration.kind==="iteration"?{iterationId:option.id}:{singleSelectOptionId:option.id};}return{kind:"update_project_item_field_value",projectId:snapshot.projectRef,itemId:issue.itemRef,fieldId:found.id,value};}
 if(operation.type==="set_issue_type"){if(typeof operation.desired!=="string")throw new ApplyPortError("invariant");return{kind:"set_issue_type",ownerLogin:snapshot.ownerLogin,repositoryName:snapshot.repositoryName,issueNumber:input.issueNumbers[0]!,issueTypeName:operation.desired};}
 if(operation.type==="set_parent"){const parent=Number(operation.desired),related=await reader.read({...input,issueNumbers:[input.issueNumbers[0]!,parent]});const parentIssue=related.issues.get(parent),child=related.issues.get(input.issueNumbers[0]!);if(!parentIssue||!child)throw new ApplyPortError("invariant");return{kind:"add_sub_issue",parentIssueId:parentIssue.issueRef,subIssueId:child.issueRef};}
 const match=operation.resource.logicalKey.match(/^(\d+)->(\d+)$/u);if(!match)throw new ApplyPortError("invariant");const from=Number(match[1]),to=Number(match[2]),related=await reader.read({...input,issueNumbers:[from,to]}),blocking=related.issues.get(from),blocked=related.issues.get(to);if(!blocking||!blocked)throw new ApplyPortError("invariant");return{kind:"add_blocked_by",blockedIssueId:blocked.issueRef,blockingIssueId:blocking.issueRef};
}

function createNativeControlledApplyHostFactory(options:ControlledApplyHostOptions):ApplyHostFactory{
 if(!options||options.coordination.epoch!==options.coordinationEpoch||options.allowedIssuerRefs.length<1||new Set(options.allowedIssuerRefs).size!==options.allowedIssuerRefs.length)throw new TypeError("invalid controlled apply host configuration");const coordinationStore=createApplyCoordinationHttpStore(options.coordination),clock=options.nowMs??Date.now;
 return{create:async(input:ApplyHostFactoryInput)=>{if(input.readToken===input.writeToken)throw new TypeError("credential profiles must be distinct");const ledger=createGitHubRateLedger(options.rate),reader=createRestProjectSnapshotReader({token:input.readToken,fetch:options.readFetch,rateLedger:ledger,graphqlRemaining:options.rate.graphqlRemaining}),snapshotInput:SnapshotInput={ownerLogin:input.requestedScope.ownerLogin,repositoryName:input.requestedScope.repositoryName,projectNumber:input.requestedScope.projectNumber,issueNumbers:[input.requestedScope.issueNumber]},mutation=createGitHubMutationTransport({token:input.writeToken,permissions:options.permissions,approvedKinds:options.approvedKinds,fetch:options.writeFetch,rateLedger:ledger});let latest:Success;
  const replan=async()=>{const prepared=await prepareReconciliation({scope:input.requestedScope,policySource:input.policySource,transport:createGitHubRestSnapshotReadTransportFromReader(reader)});if(prepared.status!=="success")return failure(prepared);latest=prepared;return prepared.plan;};
  await replan();const scope=latest!.observation.scope;return{scope,deferredReceipt:()=>{const resource=ledger.snapshot().deferredResource??"graphql",issuedAtMs=clock();return createGovernedHandoffReceipt({resource,issuedAtMs,scopeDigest:digest(scope),requestDigest:digest({scope,policyDigest:digest(input.policySource)}),planDigest:latest?.plan.planId??null,freshApprovalRequired:true});},host:{enablement:options.enablement,allowedIssuerRefs:options.allowedIssuerRefs,holderDigest:options.holderDigest,coordinationEpoch:options.coordinationEpoch,coordinationStore,ports:{nowMs:clock,replan,inspect:async operation=>{const plan=await replan(),found=plan.operations.find(candidate=>candidate.operationKey===operation.operationKey);if(found)return exact(found,operation)?"ready":"mismatch";return plan.operations.some(candidate=>sameResource(candidate,operation))?"mismatch":"already_converged";},mutate:async(kind,operation,clientMutationId)=>{if(KIND[operation.type]!==kind)throw new ApplyPortError("invariant");try{await mutation.execute(kind,await variables(operation,latest!,reader,snapshotInput),clientMutationId);}catch(error){throw normalizeGitHubApplyFailure(error);}},invalidateAfterMutation:async(kind)=>reader.invalidate(snapshotInput,snapshotInvalidationForMutation(kind)),verify:async operation=>{const plan=await replan();return!plan.operations.some(candidate=>sameResource(candidate,operation));},audit:options.audit??(async()=>{})}}};}};
}

export function createControlledApplyHostFactory(options:ControlledApplyHostOptions):ApplyHostFactory{const native=createNativeControlledApplyHostFactory(options),legacy=createControlledLegacyApplyHostFactory(options);return{create:input=>/^\s*version:\s*1\s*$/mu.test(input.policySource)?legacy.create(input):native.create(input)};}
