import { createHash } from "node:crypto";
import { canonicalJson, type BoundScope, type PlannedOperation, type ReconciliationPlan } from "./planner.js";

export type MutationKind="create_project_field"|"update_project_field_options"|"update_project_item_field_value"|"set_issue_type"|"add_sub_issue"|"add_blocked_by";
export type ApplyFailureClass="authentication"|"authorization"|"deferred_rate_budget"|"provider"|"invariant";
export class ApplyPortError extends Error{constructor(readonly failureClass:ApplyFailureClass){super("apply port failed");this.name="ApplyPortError";}}
export type ApplyCode=`YKP-APPLY-${"001"|"002"|"003"|"004"|"005"|"006"|"007"|"008"|"009"|"010"|"011"|"012"|"013"|"014"|"015"|"016"|"017"}`;
export interface ApplyDiagnostic{code:ApplyCode;severity:"error";message:string}
export interface ApprovalClaims{schema:1;issuerRef:string;subjectRef:string;repositoryRef:string;projectRef:string;issueRef:string;issueNumber:number;scopeDigest:string;planId:string;operationDigest:string;environment:"apply";protectedEnvironment:string;issuedAtMs:number;expiresAtMs:number;nonce:string;keyFingerprint:string;contractVersion:"controlled-apply-v1";plannerVersion:"reconciliation-plan-v1";snapshotVersion:"rest-project-snapshot-v2";entrypointVersion:"apply-entrypoint-v1"}
export interface Lease{readonly fencingToken:number;valid():Promise<boolean>;release():Promise<void>}
export interface ExecutorPorts{
 nowMs():number;
 verifyApproval(artifact:unknown):Promise<ApprovalClaims|null>;
 acquireLease(scopeDigest:string):Promise<Lease|null>;
 consumeNonce(nonce:string):Promise<boolean>;
 replan():Promise<ReconciliationPlan>;
 inspect(operation:PlannedOperation):Promise<"ready"|"already_converged"|"mismatch">;
 mutate(kind:MutationKind,operation:PlannedOperation,clientMutationId:string,fencingToken:number):Promise<void>;
 invalidateAfterMutation(kind:MutationKind,operation:PlannedOperation):Promise<void>;
 verify(operation:PlannedOperation):Promise<boolean>;
 audit(event:{type:string;planId:string;operationKey?:string;outcome:string}):Promise<void>;
}
export interface ApplyRequest{approvedPlanId:string;scope:BoundScope;approval:unknown;enablement:string;protectedEnvironment:string}
export type OperationOutcome="already_converged"|"verified"|"failed"|"not_attempted";
export interface ApplyResult{schema:1;status:"success"|"error"|"deferred";planId:string;outcomes:readonly{operationKey:string;outcome:OperationOutcome}[];remaining:number;diagnostics:readonly ApplyDiagnostic[]}
export interface PublicApplyReport{schema:1;status:"success"|"error"|"deferred";planId:string;counts:Record<OperationOutcome,number>;remaining:number;diagnostics:readonly ApplyDiagnostic[]}

const MESSAGE:Record<ApplyCode,string>={"YKP-APPLY-001":"apply request is invalid","YKP-APPLY-002":"apply is not explicitly enabled","YKP-APPLY-003":"approval is invalid or does not match","YKP-APPLY-004":"approval is expired or has invalid lifetime","YKP-APPLY-005":"operation is unsupported","YKP-APPLY-006":"scope lease is unavailable or lost","YKP-APPLY-007":"fresh preflight does not match approved plan","YKP-APPLY-008":"approval nonce is already consumed","YKP-APPLY-009":"operation precondition does not match","YKP-APPLY-010":"mutation attempt failed","YKP-APPLY-011":"operation verification failed","YKP-APPLY-012":"final convergence verification failed","YKP-APPLY-013":"provider authentication failed","YKP-APPLY-014":"provider authorization failed","YKP-APPLY-015":"provider budget is reserved","YKP-APPLY-016":"provider is unavailable","YKP-APPLY-017":"provider invariant is invalid"};
const MAP:Record<PlannedOperation["type"],MutationKind>={create_field:"create_project_field",add_option:"update_project_field_options",set_field_value:"update_project_item_field_value",set_parent:"add_sub_issue",add_dependency:"add_blocked_by"};
function hash(v:unknown):string{return createHash("sha256").update(canonicalJson(v)).digest("hex");}
function integrity(plan:ReconciliationPlan):boolean{if(!plan||plan.schema!==1||!plan.executable||plan.diagnostics.length!==0||!Array.isArray(plan.operations)||!Array.isArray(plan.observations))return false;const {planId,...base}=plan;return /^[a-f0-9]{64}$/u.test(planId)&&hash(base)===planId;}
function bounded(v:unknown):v is string{return typeof v==="string"&&[...v].length>0&&[...v].length<=256&&!/[\u0000-\u001f\u007f]/u.test(v);}
function validScope(s:BoundScope):boolean{return !!s&&bounded(s.subjectRef)&&bounded(s.repositoryRef)&&bounded(s.projectRef)&&bounded(s.issueRef)&&Number.isSafeInteger(s.issueNumber)&&s.issueNumber>0;}
function diag(code:ApplyCode):ApplyDiagnostic{return{code,severity:"error",message:MESSAGE[code]};}
function result(planId:string,ops:readonly PlannedOperation[],states:Map<string,OperationOutcome>,code?:ApplyCode,remaining=ops.length):ApplyResult{return{schema:1,status:code==="YKP-APPLY-015"?"deferred":code?"error":"success",planId,outcomes:ops.map(o=>({operationKey:o.operationKey,outcome:states.get(o.operationKey)??"not_attempted"})),remaining,diagnostics:code?[diag(code)]:[]};}
function portCode(error:unknown,fallback:ApplyCode):ApplyCode{if(!(error instanceof ApplyPortError))return fallback;const codes:Record<ApplyFailureClass,ApplyCode>={authentication:"YKP-APPLY-013",authorization:"YKP-APPLY-014",deferred_rate_budget:"YKP-APPLY-015",provider:"YKP-APPLY-016",invariant:"YKP-APPLY-017"};return codes[error.failureClass];}
function claimsValid(c:ApprovalClaims|null,request:ApplyRequest,now:number,scopeDigest:string):boolean{return !!c&&c.schema===1&&bounded(c.issuerRef)&&c.subjectRef===request.scope.subjectRef&&c.repositoryRef===request.scope.repositoryRef&&c.projectRef===request.scope.projectRef&&c.issueRef===request.scope.issueRef&&c.issueNumber===request.scope.issueNumber&&c.scopeDigest===scopeDigest&&c.planId===request.approvedPlanId&&/^[a-f0-9]{64}$/u.test(c.operationDigest)&&c.environment==="apply"&&bounded(c.protectedEnvironment)&&c.protectedEnvironment===request.protectedEnvironment&&Number.isSafeInteger(c.issuedAtMs)&&Number.isSafeInteger(c.expiresAtMs)&&c.issuedAtMs<=now&&c.expiresAtMs>=now&&c.expiresAtMs-c.issuedAtMs<=15*60*1000&&bounded(c.nonce)&&[...c.nonce].length>=22&&/^[a-f0-9]{64}$/u.test(c.keyFingerprint)&&c.contractVersion==="controlled-apply-v1"&&c.plannerVersion==="reconciliation-plan-v1"&&c.snapshotVersion==="rest-project-snapshot-v2"&&c.entrypointVersion==="apply-entrypoint-v1";}
function dependenciesValid(ops:readonly PlannedOperation[]):boolean{const prior=new Set<string>();for(const op of ops){if(!bounded(op.operationKey)||op.environment!=="dry-run"||op.dependsOn.some(d=>!prior.has(d)))return false;prior.add(op.operationKey);}return prior.size===ops.length;}
function operationsMatchScope(ops:readonly PlannedOperation[],scope:BoundScope):boolean{return ops.every(op=>op.subject.ref===scope.subjectRef&&(op.resource.scopeRef===scope.repositoryRef||op.resource.scopeRef===scope.projectRef));}

export async function executeControlledPlan(request:ApplyRequest,ports:ExecutorPorts):Promise<ApplyResult>{
 const planId=request?.approvedPlanId??"invalid",states=new Map<string,OperationOutcome>();let operations:readonly PlannedOperation[]=[];
 if(!validScope(request?.scope)||!/^[a-f0-9]{64}$/u.test(planId)||!bounded(request?.protectedEnvironment))return result(planId,operations,states,"YKP-APPLY-001");
 if(request.enablement!=="apply-explicitly-enabled")return result(planId,operations,states,"YKP-APPLY-002");
 const scopeDigest=hash(request.scope);let approval:ApprovalClaims|null;try{approval=await ports.verifyApproval(request.approval);}catch{return result(planId,operations,states,"YKP-APPLY-003");}
 const now=ports.nowMs();if(!claimsValid(approval,request,now,scopeDigest))return result(planId,operations,states,approval&&approval.expiresAtMs<now?"YKP-APPLY-004":"YKP-APPLY-003");
 let lease:Lease|null=null;
 try{
  try{lease=await ports.acquireLease(scopeDigest);}catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-006"));}
  if(!lease||!await lease.valid())return result(planId,operations,states,"YKP-APPLY-006");
  let fresh:ReconciliationPlan;try{fresh=await ports.replan();}catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-017"));}
  operations=fresh?.operations??[];if(!integrity(fresh)||fresh.planId!==planId||!dependenciesValid(operations)||!operationsMatchScope(operations,request.scope)||hash(operations)!==approval!.operationDigest)return result(planId,operations,states,"YKP-APPLY-007");if(operations.some(op=>!MAP[op.type]))return result(planId,operations,states,"YKP-APPLY-005");if(!await ports.consumeNonce(approval!.nonce))return result(planId,operations,states,"YKP-APPLY-008");await ports.audit({type:"apply_started",planId,outcome:"approved"});
  for(const op of operations){if(!await lease.valid()){await ports.audit({type:"apply_stopped",planId,operationKey:op.operationKey,outcome:"lease_lost"});return result(planId,operations,states,"YKP-APPLY-006");}if(op.dependsOn.some(d=>!(["verified","already_converged"] as OperationOutcome[]).includes(states.get(d)??"not_attempted")))return result(planId,operations,states,"YKP-APPLY-009");let observed:Awaited<ReturnType<ExecutorPorts["inspect"]>>;try{observed=await ports.inspect(op);}catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-009"));}if(observed==="already_converged"){states.set(op.operationKey,"already_converged");await ports.audit({type:"operation",planId,operationKey:op.operationKey,outcome:"already_converged"});continue;}if(observed!=="ready"){states.set(op.operationKey,"failed");return result(planId,operations,states,"YKP-APPLY-009");}if(!Number.isSafeInteger(lease.fencingToken)||lease.fencingToken<1||!await lease.valid())return result(planId,operations,states,"YKP-APPLY-006");const mutationKind=MAP[op.type];try{await ports.mutate(mutationKind,op,hash([planId,op.operationKey]).slice(0,64),lease.fencingToken);}catch(error){states.set(op.operationKey,"failed");await ports.audit({type:"operation",planId,operationKey:op.operationKey,outcome:"failed"});return result(planId,operations,states,portCode(error,"YKP-APPLY-010"));}let verified=false;try{await ports.invalidateAfterMutation(mutationKind,op);verified=await ports.verify(op);}catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-011"));}if(!verified){states.set(op.operationKey,"failed");return result(planId,operations,states,"YKP-APPLY-011");}states.set(op.operationKey,"verified");await ports.audit({type:"operation",planId,operationKey:op.operationKey,outcome:"verified"});}
  let finalPlan:ReconciliationPlan;try{finalPlan=await ports.replan();}catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-012"));}if(!integrity(finalPlan)||!finalPlan.executable||finalPlan.operations.length!==0||finalPlan.diagnostics.length!==0)return result(planId,operations,states,"YKP-APPLY-012",finalPlan.operations.length);await ports.audit({type:"apply_finished",planId,outcome:"verified"});return result(planId,operations,states,undefined,0);
 }catch(error){return result(planId,operations,states,portCode(error,"YKP-APPLY-012"));}finally{if(lease)try{await lease.release();}catch{/* release cannot turn an unsafe result into success */}}
}
export function renderPublicApplyReport(value:ApplyResult):PublicApplyReport{const counts:Record<OperationOutcome,number>={already_converged:0,verified:0,failed:0,not_attempted:0};for(const item of value.outcomes)counts[item.outcome]++;return{schema:1,status:value.status,planId:value.planId,counts,remaining:value.remaining,diagnostics:value.diagnostics.map(d=>({...d}))};}
