import type { AllowedReadOperation, GitHubReadCode, SnapshotReadCode, ReadEnvelope, ReadOnlyTransport } from "./github-readonly.js";

const ENDPOINT = "https://api.github.com/graphql";
const DOCUMENTS: Record<AllowedReadOperation,string> = {
 resolve_scope: `query YukhResolveScope($ownerLogin:String!,$repositoryName:String!,$projectNumber:Int!,$issueNumber:Int!){viewer{login}repository(owner:$ownerLogin,name:$repositoryName){id issue(number:$issueNumber){id number body projectItems(first:100){nodes{id project{id number}}pageInfo{hasNextPage}}}}repositoryOwner(login:$ownerLogin){... on User{projectV2(number:$projectNumber){id number}}... on Organization{projectV2(number:$projectNumber){id number}}}}`,
 read_project_fields: `query YukhReadProjectFields($ownerLogin:String!,$projectNumber:Int!,$first:Int!,$cursor:String){repositoryOwner(login:$ownerLogin){... on User{projectV2(number:$projectNumber){id fields(first:$first,after:$cursor){nodes{... on ProjectV2Field{id name dataType}... on ProjectV2SingleSelectField{id name dataType options{id name}}... on ProjectV2IterationField{id name dataType configuration{iterations{id title}completedIterations{id title}}}}pageInfo{hasNextPage endCursor}}}}... on Organization{projectV2(number:$projectNumber){id fields(first:$first,after:$cursor){nodes{... on ProjectV2Field{id name dataType}... on ProjectV2SingleSelectField{id name dataType options{id name}}... on ProjectV2IterationField{id name dataType configuration{iterations{id title}completedIterations{id title}}}}pageInfo{hasNextPage endCursor}}}}}}`,
 read_project_item: `query YukhReadProjectItem($ownerLogin:String!,$repositoryName:String!,$issueNumber:Int!,$first:Int!,$cursor:String){repository(owner:$ownerLogin,name:$repositoryName){issue(number:$issueNumber){id projectItems(first:100){nodes{id project{id number}fieldValues(first:$first,after:$cursor){nodes{... on ProjectV2ItemFieldTextValue{text field{... on ProjectV2FieldCommon{name}}}... on ProjectV2ItemFieldNumberValue{number field{... on ProjectV2FieldCommon{name}}}... on ProjectV2ItemFieldDateValue{date field{... on ProjectV2FieldCommon{name}}}... on ProjectV2ItemFieldSingleSelectValue{name field{... on ProjectV2FieldCommon{name}}}... on ProjectV2ItemFieldIterationValue{title field{... on ProjectV2FieldCommon{name}}}}pageInfo{hasNextPage endCursor}}}pageInfo{hasNextPage}}}}}`,
 read_issue_relationships: `query YukhReadIssueRelationships($ownerLogin:String!,$repositoryName:String!,$issueNumber:Int!,$first:Int!,$cursor:String){repository(owner:$ownerLogin,name:$repositoryName){id issue(number:$issueNumber){id number parent{number repository{id}}subIssues(first:$first,after:$cursor){nodes{number repository{id}}pageInfo{hasNextPage endCursor}}blockedBy(first:$first,after:$cursor){nodes{number repository{id}}pageInfo{hasNextPage endCursor}}blocking(first:$first,after:$cursor){nodes{number repository{id}}pageInfo{hasNextPage endCursor}}}}}`
};
export const GITHUB_READ_QUERY_DOCUMENTS:Readonly<Record<AllowedReadOperation,string>> = Object.freeze({...DOCUMENTS});
export class GitHubTransportError extends Error { constructor(readonly code:GitHubReadCode|SnapshotReadCode){super("GitHub read transport failed");this.name="GitHubTransportError";} }
export interface GitHubTransportOptions { token:string; fetch?:typeof globalThis.fetch }
function rec(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v);}
function obj(v:unknown,key:string):Record<string,unknown>{if(!rec(v))throw new GitHubTransportError("YKP-GH-READ-008");const x=v[key];if(!rec(x))throw new GitHubTransportError("YKP-GH-READ-008");return x;}
function pageInfo(v:Record<string,unknown>):Record<string,unknown>{return obj(v,"pageInfo");}
function nodes(v:Record<string,unknown>):Record<string,unknown>[] {if(!Array.isArray(v.nodes)||!v.nodes.every(rec))throw new GitHubTransportError("YKP-GH-READ-008");return v.nodes;}
function project(owner:Record<string,unknown>):Record<string,unknown>{const p=owner.projectV2;if(!rec(p))throw new GitHubTransportError("YKP-GH-READ-006");return p;}
function ownerProject(data:Record<string,unknown>):Record<string,unknown>{return project(obj(data,"repositoryOwner"));}
function value(node:Record<string,unknown>):unknown{return node.text??node.number??node.date??node.name??node.title??null;}
function fieldKind(value:unknown):string{const kinds:Record<string,string>={TEXT:"text",NUMBER:"number",DATE:"date",SINGLE_SELECT:"single_select",ITERATION:"iteration"};const kind=kinds[String(value)];if(!kind)throw new GitHubTransportError("YKP-GH-READ-008");return kind;}
function fieldOptions(field:Record<string,unknown>):{id:unknown;name:unknown}[]{if(Array.isArray(field.options))return field.options.filter(rec).map(option=>({id:option.id,name:option.name}));if(rec(field.configuration)){const active=Array.isArray(field.configuration.iterations)?field.configuration.iterations.filter(rec):[];const completed=Array.isArray(field.configuration.completedIterations)?field.configuration.completedIterations.filter(rec):[];return [...active,...completed].map(iteration=>({id:iteration.id,name:iteration.title}));}return [];}

export function createGitHubGraphQLReadTransport(options:GitHubTransportOptions):ReadOnlyTransport{
 if(typeof options?.token!=="string"||options.token.length===0||/[\u0000-\u001f\u007f]/u.test(options.token))throw new TypeError("invalid credential");const request=options.fetch??globalThis.fetch;
 return {execute:async(operation,variables):Promise<ReadEnvelope>=>{
  const query=DOCUMENTS[operation];if(!query||!/^query Yukh/u.test(query)||/\bmutation\b|\bsubscription\b/u.test(query))throw new GitHubTransportError("YKP-GH-READ-010");
  let response:Response;try{response=await request(ENDPOINT,{method:"POST",redirect:"manual",headers:{accept:"application/vnd.github+json","content-type":"application/json","authorization":`Bearer ${options.token}`,"x-github-api-version":"2022-11-28"},body:JSON.stringify({query,variables})});}catch{throw new GitHubTransportError("YKP-GH-READ-004");}
  if(response.status>=300&&response.status<400)throw new GitHubTransportError("YKP-GH-READ-006");if(response.status===401)throw new GitHubTransportError("YKP-GH-READ-002");if(response.status===403)throw new GitHubTransportError(response.headers.get("x-ratelimit-remaining")==="0"?"YKP-GH-READ-009":"YKP-GH-READ-003");if(response.status===429)throw new GitHubTransportError("YKP-GH-READ-009");if([502,503,504].includes(response.status))throw new GitHubTransportError("YKP-GH-READ-004");if(!response.ok)throw new GitHubTransportError("YKP-GH-READ-008");if(!response.headers.get("content-type")?.toLowerCase().includes("application/json"))throw new GitHubTransportError("YKP-GH-READ-008");
  const raw=new Uint8Array(await response.arrayBuffer());if(raw.byteLength>2*1024*1024)throw new GitHubTransportError("YKP-GH-READ-005");let body:unknown;try{body=JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(raw));}catch{throw new GitHubTransportError("YKP-GH-READ-008");}if(!rec(body)||!rec(body.data))throw new GitHubTransportError(Array.isArray((body as Record<string,unknown>)?.errors)?"YKP-GH-READ-003":"YKP-GH-READ-008");const data=body.data;
  let normalized:unknown;
  if(operation==="resolve_scope"){const viewer=obj(data,"viewer"),repo=obj(data,"repository"),issue=obj(repo,"issue"),p=ownerProject(data),items=obj(issue,"projectItems");if(typeof viewer.login!=="string"||!/^[A-Za-z0-9-]{1,39}$/u.test(viewer.login))throw new GitHubTransportError("YKP-GH-READ-008");if(pageInfo(items).hasNextPage===true)throw new GitHubTransportError("YKP-GH-READ-005");if(typeof issue.body!=="string")throw new GitHubTransportError("YKP-GH-READ-008");if(Buffer.byteLength(issue.body,"utf8")>256*1024)throw new GitHubTransportError("YKP-GH-READ-005");const matches=nodes(items).filter(i=>rec(i.project)&&i.project.id===p.id);if(matches.length>1)throw new GitHubTransportError("YKP-GH-READ-006");normalized={subjectRef:`github:${viewer.login}`,ownerLogin:variables.ownerLogin,repositoryName:variables.repositoryName,projectNumber:p.number,issueNumber:issue.number,repositoryRef:repo.id,projectRef:p.id,issueRef:issue.id,issueBody:issue.body};}
  else if(operation==="read_project_fields"){const p=ownerProject(data),fields=obj(p,"fields");normalized={projectRef:p.id,nodes:nodes(fields).map(f=>({id:f.id,name:f.name,kind:fieldKind(f.dataType),options:fieldOptions(f)})),pageInfo:pageInfo(fields)};}
  else if(operation==="read_project_item"){const issue=obj(obj(data,"repository"),"issue"),items=obj(issue,"projectItems");if(pageInfo(items).hasNextPage===true)throw new GitHubTransportError("YKP-GH-READ-005");const matches=nodes(items).filter(i=>rec(i.project)&&i.project.number===variables.projectNumber);if(matches.length===0)normalized={projectRef:null,issueRef:issue.id,absent:true,nodes:[],pageInfo:{hasNextPage:false,endCursor:null}};else{if(matches.length!==1)throw new GitHubTransportError("YKP-GH-READ-006");const item=matches[0]!,values=obj(item,"fieldValues");normalized={projectRef:(item.project as Record<string,unknown>).id,issueRef:issue.id,itemRef:item.id,fingerprint:item.id,nodes:nodes(values).filter(v=>rec(v.field)&&typeof (v.field as Record<string,unknown>).name==="string").map(v=>({key:(v.field as Record<string,unknown>).name,value:value(v)})),pageInfo:pageInfo(values)};}}
  else {const repo=obj(data,"repository"),issue=obj(repo,"issue"),connections=[obj(issue,"subIssues"),obj(issue,"blockedBy"),obj(issue,"blocking")],infos=connections.map(pageInfo),next=infos.filter(i=>i.hasNextPage===true).map(i=>i.endCursor);if(next.length>0&&new Set(next).size!==1)throw new GitHubTransportError("YKP-GH-READ-007");const related=[...nodes(connections[0]!),...nodes(connections[1]!),...nodes(connections[2]!)],all=[{issueNumber:issue.number},...related.map(i=>({issueNumber:i.number}))];const unique=[...new Map(all.map(i=>[i.issueNumber,i])).values()];const parent=rec(issue.parent)?[{from:issue.number,to:issue.parent.number}]:[];const blocked=nodes(connections[1]!).map(i=>({from:i.number,to:issue.number}));const blocking=nodes(connections[2]!).map(i=>({from:issue.number,to:i.number}));normalized={repositoryRef:repo.id,issueRef:issue.id,nodes:unique,parent,blocks:[...blocked,...blocking],pageInfo:{hasNextPage:next.length>0,endCursor:next[0]??null}};}
  return {byteCount:raw.byteLength,data:normalized};
 }};
}
