import { createHash } from "node:crypto";
import { canonicalJson, type ObservedItem, type ObservedRelationshipGraph, type ObservedValue, type RelationshipEdge } from "./planner.js";

export const READ_OPERATIONS = ["resolve_scope", "read_project_fields", "read_project_item", "read_issue_relationships"] as const;
export type AllowedReadOperation = typeof READ_OPERATIONS[number];
export interface RequestedGitHubScope { ownerLogin: string; repositoryName: string; projectNumber: number; issueNumber: number }
export interface ReadEnvelope { byteCount: number; data: unknown }
export interface ReadOnlyTransport { execute(operation: AllowedReadOperation, variables: Readonly<Record<string, unknown>>): Promise<ReadEnvelope> }
export type GitHubReadCode = `YKP-GH-READ-${"001"|"002"|"003"|"004"|"005"|"006"|"007"|"008"|"009"|"010"|"011"}`;
export interface GitHubReadDiagnostic { code: GitHubReadCode; severity: "error"; message: string; operation: AllowedReadOperation | "scope"; retry: "never"|"repair"|"full-read"|"reset"|"review" }
export interface ObservedProjectSchema { fields: readonly { id: string; name: string; kind: "text"|"number"|"date"|"single_select"|"iteration"; options: readonly { id:string; name:string }[] }[] }
export interface GitHubObservation { scope: { subjectRef: string; repositoryRef: string; projectRef: string; issueRef: string; issueNumber: number }; issueBody: string; projectSchema: ObservedProjectSchema; item: ObservedItem|null; relationships: ObservedRelationshipGraph; evidence: { schema: 1; operationCounts: Record<AllowedReadOperation,number>; pageCount: number; fingerprint: string } }
export type GitHubReadResult = { observation: GitHubObservation; diagnostics: readonly [] } | { observation:null; diagnostics:readonly GitHubReadDiagnostic[] };

const MSG:Record<GitHubReadCode,string>={"YKP-GH-READ-001":"requested scope is invalid","YKP-GH-READ-002":"authentication failed","YKP-GH-READ-003":"access is denied","YKP-GH-READ-004":"provider is unavailable","YKP-GH-READ-005":"response limit is exceeded","YKP-GH-READ-006":"resource binding does not match","YKP-GH-READ-007":"pagination invariant is invalid","YKP-GH-READ-008":"provider response is invalid","YKP-GH-READ-009":"provider rate limit is reached","YKP-GH-READ-010":"failure could not be safely classified","YKP-GH-READ-011":"required provider capability is unavailable"};
function failure(code:GitHubReadCode,operation:GitHubReadDiagnostic["operation"],retry:GitHubReadDiagnostic["retry"]="never"):GitHubReadResult{return{observation:null,diagnostics:[{code,severity:"error",message:MSG[code],operation,retry}]};}
function rec(v:unknown):v is Record<string,unknown>{return typeof v==="object"&&v!==null&&!Array.isArray(v);}
function text(v:unknown,max=256):v is string{return typeof v==="string"&&v.trim()===v&&[...v].length>0&&[...v].length<=max&&!/[\u0000-\u001f\u007f]/u.test(v);}
function scopeOK(s:RequestedGitHubScope):boolean{return !!s&&text(s.ownerLogin)&&text(s.repositoryName)&&Number.isSafeInteger(s.projectNumber)&&s.projectNumber>0&&Number.isSafeInteger(s.issueNumber)&&s.issueNumber>0;}
type Page={nodes:unknown[];pageInfo:{hasNextPage:boolean;endCursor:string|null}};
type ValidPage=Page&Record<string,unknown>;
function page(v:unknown):v is Page{return rec(v)&&Array.isArray(v.nodes)&&rec(v.pageInfo)&&typeof v.pageInfo.hasNextPage==="boolean"&&(v.pageInfo.endCursor===null||text(v.pageInfo.endCursor));}
class ReadFailure { constructor(readonly code:GitHubReadCode,readonly operation:AllowedReadOperation){} }

export async function readGitHubObservation(scope:RequestedGitHubScope,transport:ReadOnlyTransport):Promise<GitHubReadResult>{
 if(!scopeOK(scope))return failure("YKP-GH-READ-001","scope");
 const counts=Object.fromEntries(READ_OPERATIONS.map(k=>[k,0])) as Record<AllowedReadOperation,number>;let bytes=0,pages=0;
 const execute=async(op:AllowedReadOperation,cursor:string|null):Promise<Record<string,unknown>>=>{counts[op]++;const e=await transport.execute(op,Object.freeze({ownerLogin:scope.ownerLogin,repositoryName:scope.repositoryName,projectNumber:scope.projectNumber,issueNumber:scope.issueNumber,cursor,first:50}));pages++;if(!Number.isSafeInteger(e?.byteCount)||e.byteCount<0||e.byteCount>2*1024*1024||(bytes+=e.byteCount)>16*1024*1024)throw new ReadFailure("YKP-GH-READ-005",op);if(!rec(e.data))throw new ReadFailure("YKP-GH-READ-008",op);return e.data;};
 try{
  const resolved=await execute("resolve_scope",null);if(resolved.ownerLogin!==scope.ownerLogin||resolved.repositoryName!==scope.repositoryName||resolved.projectNumber!==scope.projectNumber||resolved.issueNumber!==scope.issueNumber||!text(resolved.subjectRef)||!text(resolved.repositoryRef)||!text(resolved.projectRef)||!text(resolved.issueRef))throw new ReadFailure("YKP-GH-READ-006","resolve_scope");if(typeof resolved.issueBody!=="string")throw new ReadFailure("YKP-GH-READ-008","resolve_scope");if(Buffer.byteLength(resolved.issueBody,"utf8")>256*1024)throw new ReadFailure("YKP-GH-READ-005","resolve_scope");
  const paginate=async(op:Exclude<AllowedReadOperation,"resolve_scope">):Promise<ValidPage[]>=>{const out:ValidPage[]=[];const cursors=new Set<string>();let cursor:string|null=null;for(let n=0;n<20;n++){const data=await execute(op,cursor);if(!page(data))throw new ReadFailure("YKP-GH-READ-008",op);out.push(data);if(!data.pageInfo.hasNextPage)return out;const next=data.pageInfo.endCursor;if(!next||cursors.has(next)||next===cursor)throw new ReadFailure("YKP-GH-READ-007",op);cursors.add(next);cursor=next;}throw new ReadFailure("YKP-GH-READ-005",op);};
  const fieldPages=await paginate("read_project_fields"),itemPages=await paginate("read_project_item"),relationPages=await paginate("read_issue_relationships");
  const fields:ObservedProjectSchema["fields"] extends readonly (infer T)[]?T[]:never=[];const fieldIds=new Set<string>(),optionIds=new Set<string>();let optionCount=0;for(const p of fieldPages){if(p.projectRef!==resolved.projectRef)throw new ReadFailure("YKP-GH-READ-006","read_project_fields");for(const v of p.nodes){if(!rec(v)||!text(v.id)||!text(v.name)||!["text","number","date","single_select","iteration"].includes(String(v.kind))||fieldIds.has(v.id)||!Array.isArray(v.options)||v.options.length>256)throw new ReadFailure("YKP-GH-READ-008","read_project_fields");fieldIds.add(v.id);const options:{id:string;name:string}[]=[];for(const o of v.options){if(!rec(o)||!text(o.id)||!text(o.name)||optionIds.has(o.id))throw new ReadFailure("YKP-GH-READ-008","read_project_fields");optionIds.add(o.id);options.push({id:o.id,name:o.name});if(++optionCount>2048)throw new ReadFailure("YKP-GH-READ-005","read_project_fields");}options.sort((a,b)=>a.id.localeCompare(b.id));fields.push({id:v.id,name:v.name,kind:v.kind as typeof fields[number]["kind"],options});if(fields.length>256)throw new ReadFailure("YKP-GH-READ-005","read_project_fields");}}
  let item:ObservedItem|null=null;const values:Record<string,ObservedValue>={};let itemRef:string|undefined,fingerprint:string|undefined;for(const p of itemPages){if(p.issueRef!==resolved.issueRef)throw new ReadFailure("YKP-GH-READ-006","read_project_item");if(p.absent===true){if(p.nodes.length||itemRef)throw new ReadFailure("YKP-GH-READ-008","read_project_item");continue;}if(p.projectRef!==resolved.projectRef||!text(p.itemRef)||!text(p.fingerprint)||itemRef&&p.itemRef!==itemRef||fingerprint&&p.fingerprint!==fingerprint)throw new ReadFailure("YKP-GH-READ-006","read_project_item");itemRef=p.itemRef;fingerprint=p.fingerprint;for(const v of p.nodes){if(!rec(v)||!text(v.key,64)||v.key in values||!(v.value===null||typeof v.value==="string"||typeof v.value==="number"&&Number.isFinite(v.value)))throw new ReadFailure("YKP-GH-READ-008","read_project_item");values[v.key]=v.value as ObservedValue;if(Object.keys(values).length>256)throw new ReadFailure("YKP-GH-READ-005","read_project_item");}}if(itemRef&&fingerprint)item={values,fingerprint};
  const nodes=new Set<number>(),parents:RelationshipEdge[]=[],blocks:RelationshipEdge[]=[];const edges=new Set<string>();for(const p of relationPages){if(p.repositoryRef!==resolved.repositoryRef||p.issueRef!==resolved.issueRef)throw new ReadFailure("YKP-GH-READ-006","read_issue_relationships");for(const v of p.nodes){if(!rec(v)||!Number.isSafeInteger(v.issueNumber)||(v.issueNumber as number)<=0||nodes.has(v.issueNumber as number))throw new ReadFailure("YKP-GH-READ-008","read_issue_relationships");nodes.add(v.issueNumber as number);if(nodes.size>512)throw new ReadFailure("YKP-GH-READ-005","read_issue_relationships");}for(const [key,target,limit] of [["parent",parents,511],["blocks",blocks,4096]] as const){const list=p[key];if(!Array.isArray(list))throw new ReadFailure("YKP-GH-READ-008","read_issue_relationships");for(const e of list){if(!rec(e)||!Number.isSafeInteger(e.from)||!Number.isSafeInteger(e.to))throw new ReadFailure("YKP-GH-READ-008","read_issue_relationships");const id=`${key}:${e.from}->${e.to}`;if(edges.has(id))throw new ReadFailure("YKP-GH-READ-008","read_issue_relationships");edges.add(id);target.push({from:e.from as number,to:e.to as number});if(target.length>limit)throw new ReadFailure("YKP-GH-READ-005","read_issue_relationships");}}}
  if(!nodes.has(scope.issueNumber)||[...parents,...blocks].some(e=>!nodes.has(e.from)||!nodes.has(e.to)||e.from===e.to))throw new ReadFailure("YKP-GH-READ-006","read_issue_relationships");
  fields.sort((a,b)=>a.id.localeCompare(b.id));const relationships={nodes:[...nodes].sort((a,b)=>a-b),parent:parents.sort((a,b)=>a.from-b.from||a.to-b.to),blocks:blocks.sort((a,b)=>a.from-b.from||a.to-b.to)};const base={scope:{subjectRef:resolved.subjectRef as string,repositoryRef:resolved.repositoryRef as string,projectRef:resolved.projectRef as string,issueRef:resolved.issueRef as string,issueNumber:scope.issueNumber},projectSchema:{fields},item,relationships};const fingerprintOut=createHash("sha256").update(canonicalJson(base)).digest("hex");return{observation:{...base,issueBody:resolved.issueBody,evidence:{schema:1,operationCounts:counts,pageCount:pages,fingerprint:fingerprintOut}},diagnostics:[]};
 }catch(e){if(e instanceof ReadFailure)return failure(e.code,e.operation,e.code==="YKP-GH-READ-008"?"review":"never");if(rec(e)&&typeof e.code==="string"&&Object.hasOwn(MSG,e.code)){const code=e.code as GitHubReadCode;return failure(code,"scope",code==="YKP-GH-READ-004"?"full-read":code==="YKP-GH-READ-009"?"reset":code==="YKP-GH-READ-008"?"review":"never");}return failure("YKP-GH-READ-004","scope","full-read");}
}
