import { createHash } from "node:crypto";

export interface ReleaseArtifact { path:string; bytes:Uint8Array }
export interface WouldPublishManifest { schema:1;version:string;commit:string;tag:string;artifacts:readonly {path:string;sha256:string;bytes:number}[];publication:"disabled" }
const RELEASE_ARTIFACTS=new Set(["RELEASE_NOTES.md","action.yml","apply-action.yml","dist/action/index.js","dist/apply/action.js","dist/apply/cli.js","dist/apply/index.js","dist/apply/manifest.json","dist/cli/index.js","package-lock.json","release.spdx.json"]);
export function createWouldPublishManifest(version:string,commit:string,packageVersion:string,changelog:string,artifacts:readonly ReleaseArtifact[]):WouldPublishManifest{
 if(!/^(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)$/u.test(version)||packageVersion!==version||!/^[0-9a-f]{40}$/u.test(commit)||!new RegExp(`^## (?:\\[)?${version.replaceAll(".","\\.")}(?:\\])?(?:$|\\s|\\()`,"mu").test(changelog))throw new TypeError("release candidate is invalid");
 const seen=new Set<string>();let releaseNotes:Uint8Array|undefined;const normalized=artifacts.map(artifact=>{if(!RELEASE_ARTIFACTS.has(artifact.path)||seen.has(artifact.path)||artifact.bytes.byteLength===0)throw new TypeError("release artifact is invalid");seen.add(artifact.path);if(artifact.path==="RELEASE_NOTES.md")releaseNotes=artifact.bytes;return{path:artifact.path,sha256:createHash("sha256").update(artifact.bytes).digest("hex"),bytes:artifact.bytes.byteLength};}).sort((a,b)=>a.path.localeCompare(b.path));if(normalized.length!==RELEASE_ARTIFACTS.size||[...RELEASE_ARTIFACTS].some(path=>!seen.has(path))||!releaseNotes)throw new TypeError("release artifact set is incomplete");const notes=new TextDecoder("utf-8",{fatal:true}).decode(releaseNotes);if(!notes.startsWith(`# Yukh Projects ${version}\n`)||!notes.includes("## Compatibility\n")||!notes.includes("## Rollback\n"))throw new TypeError("release notes are invalid");return{schema:1,version,commit,tag:`v${version}`,artifacts:normalized,publication:"disabled"};
}
